### ISSUE TITLE
Scrabble score: test against nil forces in wrong direction

### ISSUE THREAD

**Issue by giulp** [exercism/ruby#1001]
The code,imho, should really not expect to be given 'nil' forceably, and should fail if that happens. 

Indeed, there should probably be some programming in there that purposefully raises an error. 

this test is misleading

```ruby

  def test_nil_scores_zero
    skip
    assert_equal 0, Scrabble.new(nil).score
  end

```

maybe it could be substituted with something like

```ruby

  def test_nothing_given_nothing_scores_zero
    skip
    assert_equal 0, Scrabble.new.score
  end

```

**Comment by kotp** [comment]
I agree, the exercise is not about what to do when you are given bad data, and this is just bad data, in my opinion.

I am going to assign this to you, and label it.

**Comment by kytrinyx** [comment]
This test disappeared the last time we synced with problem-specifications (see #1411).
