### ISSUE TITLE
Recruiting additional maintainers for Ruby

### ISSUE THREAD

**Issue by kytrinyx** [exercism/ruby#1017]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by pvcarrera** [comment]
I did some small contributions to exercism and mentoring in the Ruby track in the past, but I haven't done anything in quite a while. I'm always thinking about coming back to this awesome community so I guess this is the perfect excuse

**Comment by camfilho** [comment]
Hello,
I've never contributed to exercism.io before but I want to see if I can help.
I'm a Ruby developer and I really love exercism.io community :)

**Comment by kotp** [comment]
Handle is same on Exercism as it is here.  I still have hours available to assist and being available to maintainers for this track.

**Comment by pgaspar** [comment]
Hey all,
I've been radio silent for a while now - sorry. I think "won't have that time, but still want to be a maintainer and just help where you can instead" applies to me. I think my best contributions as a maintainer have been implementing exercises, so I'll be looking out for that!

**Comment by etiennemustow** [comment]
Hey, 
I loved the java track and used it for my work and have most of my professional experience in ruby so I'd be happy to be a maintainer for the ruby track. I'm currently a software craftsperson apprentice @codurance. My exercism handle is the same as here - @etiennemustow

**Comment by goalaleo** [comment]
Hi,
I've been on exercism for a year, and have mentored the ruby track for about 5 months now. I have a personal goal for 2020 of contributing to an OSS project, and can't think of a better project than exercism :) I build Rails apps for work @kiskolabs

**Comment by compostbrain** [comment]
Hi, 
I've been doing mentoring in the ruby track for a month or so.  I would like to contribute as a maintainer, if it is needed.  I do mostly ruby on rails for my day job.  Me exercism handle is the same as here...

**Comment by shairyar** [comment]
Hi,

I would like to be a part of this, I have been working with Ruby and Rails for a while now, in the past I have not been that active by contributing to OSS but now I am ready to change that.

**Comment by twwright** [comment]
Hey, all!

I started mentoring on Exercism a few weeks ago. Honestly, I'm only a few months into learning Ruby myself---although I'm already a stickler for clean, idiomatic code. I spent the last decade between doing academic research on formal logic and teaching mathematics. I'd love to contribute to an open-source project that supports folks on their learning journey.

While my development and programming experience is nowhere near most of you, my background as a teacher and a "recent Ruby learner" would be a net benefit to the project. I'm especially interested in supporting any restructure of track anatomy, examining the efficacy of exercises, and participating in the design of any potential expansions (popular frameworks? writing tests? templating engines?).

My handle on Exercism (and the Exercism Slack!) is the same as it is here: twwright

**Comment by iHiD** [comment]
@twwright Awesome. Thanks! 

Would you mind emailing me at jeremy@exercism.io just referencing this post and I'll get you set up? I'm mid laptop-setup right now which is making me normal flow for volunteers difficult. Thanks!

**Comment by biancapower** [comment]
Hello!

I'm coming to this thread a bit late, but I'd love to get involved as a maintainer, and can commit to 2-3hrs per week. I teach web development to beginner programmers (including Ruby and Rails), and have just started mentoring Ruby on Exercism. I've done a number of Exercism challenges myself as well.

My Exercism handle: biancapower

**Comment by anaschwendler** [comment]
Hello, I know I'm quite late for the thread, but I've doing exercism exercises for the past two months mostly everyday :)

I would love to join the ruby track and I can commit for 2-4 hours/week for sure :)
If there is still space, I would be very happy to join for mentoring/maintaining.

My handler on exercism is: yogibear

**Comment by kotp** [comment]
You will want to join the Slack.  [#track-ruby](https://exercism-team.slack.com/archives/CARVB5V0R) and [#maintaining-ruby](https://exercism-team.slack.com/archives/CC39FFMU0) and a few others.  You can [#start-here](https://exercism-team.slack.com/archives/CBDA9LMDF) and make [#introductions](https://exercism-team.slack.com/archives/CANSV7CVB) here.

**Comment by iHiD** [comment]
Hey @anaschwendler. Thanks for wanting to help - that's great!

Can you email me at jeremy@exercism.io and I'll send you an invite to Slack to get you in please? :)

**Comment by NeimadTL** [comment]
Hi everyone, I'm kind of late too like @anaschwendler . Are maintainers still needed please ? Should I email you @iHiD ? Thanks.

**Comment by kotp** [comment]
Definitely join the Slack. @iHiD is out for the next 10 days or so.

You are welcome to help out here!

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our push to implement the v3 version of this track and v3 has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

New maintainer are always welcome though!
