### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by porkostomus** [exercism/ruby#1025]
I found the [instructions](http://tutorials.jumpstartlab.com/topics/environment/environment.html) linked to on `INSTALLATION.md` a bit confusing, particularly from a Linux perspective - it is focused on Rails development, and has the user install Postgres. Then I was led to a strange tutorial about installing Vagrant, and finally just went to the official ruby [guide](https://www.ruby-lang.org/en/documentation/installation/) which simply told me to use my package manager which just worked! IMO the official docs do a much better job.

**Comment by kotp** [comment]
Very much Jumpstart oriented.  I had a hard time seeing the Rails connection, until they mentioned it in relationship to the database they chose to suggest.

Did you really install Postgres?  Sorry about that, not necessary for Ruby and not necessary for the Ruby track.

I agree that is a lot of information to digest, and would for sure be the wrong information to give to someone that is new to programming.

Yes, I think the Ruby guide is a much more reasonable resource, as I am sure the other instructions are more for a specific development environment... and we are more concerned with pretty plain Ruby.

Please do review the pull request that is mentioned in this issue.

**Comment by xxylem** [comment]
Hi, just to add that I had a similar problem to @porkostomus, the old installation instructions for Windows lead to [http://railsinstaller.org/en](url), which ends up giving you Ruby 2.3. It looks like #1026 provided by @kotp will fix this.

**Comment by kotp** [comment]
If someone from @exercism/ruby will approve it, it should be in shortly after that.
