### ISSUE TITLE
[Microwave]  Is this test right ?

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/ruby#1034]
Hello, 

I wonder if this test is allright 

def test_one_minute
    skip
    assert_equal '01:00', Microwave.new(100).timer
  end

100 seconds is not equal to 1 minute. 1 minute has 60 seconds 

Roelof

**Comment by twwright** [comment]
Hey @RoelofWobben!

You are correct, 100 seconds is not equal to 1:00. However, the idea of the problem set is to solve how microwaves handle input. When you use your microwave, you probably type "1" then "0" then "0". The input is 100, but the microwave automatically converts this into the 00:00 format, and it reads 01:00. Take out the colon, and that's 0100... 100! 

The test here is asserting that an entry of 100 should put the microwave at 01:00, which is really 60 seconds! Sneaky, huh?

Looks like this test works fine. Let me know if you have any other questions!

Thanks so much!
-Thomas

**Comment by kotp** [comment]
Emulating input by the user, when hitting <kbd>1</kbd><kbd>0</kbd><kbd>0</kbd><kbd>START</kbd> it should have 60 seconds.

See [this thread](https://github.com/exercism/ruby/pull/1031#discussion_r431523244) in the pull request.

**Comment by RoelofWobben** [comment]
oke, thanks for the clarification
