### ISSUE TITLE
There are two errors in the expected result on the Ruby track tests suite, Transpose challenge.

### ISSUE THREAD

**Issue by matheusma37** [exercism/ruby#1040]
* The first is at the test test_first_line_longer_than_second_line. A space is missing at the end of the expected result: it is currently `"TT\nhh\nee\n \nff\noi\nuf\nrt\nth\nh \n l\nli\nin\nne\ne.\n."`, when it should be `"TT\nhh\nee\n \nff\noi\nuf\nrt\nth\nh \n l\nli\nin\nne\ne.\n. "`.
* The second is at the test test_mixed_line_length. The expected result is defined as `"TAAA\nh \nelll\n ooi\nlnnn\nogge\nn e.\nglr\nei \nsnl\ntei\n .n\nl e\ni .\nn\ne\n."`, but the result should be `"TAAA\nh \nelll\n ooi\nlnnn\nogge\nn e.\nglr \nei \nsnl \ntei \n .n \nl e \ni . \nn \ne \n. "`.

[The modified file with the corrections](https://github.com/exercism/ruby/files/5302550/transpose_test.txt)

Thank you for your attention and my best regards.

**Comment by kotp** [comment]
Here are the changes suggested.

```diff
diff --git i/exercises/transpose/transpose_test.rb w/exercises/transpose/transpose_test.rb
index 44450d81..e11f9229 100644
--- i/exercises/transpose/transpose_test.rb
+++ w/exercises/transpose/transpose_test.rb
@@ -1,4 +1,5 @@
 require 'minitest/autorun'
+require 'minitest/pride'
 require_relative 'transpose'
 
 # Common test data version: 1.1.0 92bc877
@@ -51,8 +52,8 @@ class TransposeTest < Minitest::Test
   def test_first_line_longer_than_second_line
     skip
     input = "The fourth line.\nThe fifth line."
-
-    expected = "TT\nhh\nee\n  \nff\noi\nuf\nrt\nth\nh \n l\nli\nin\nne\ne.\n."
+    # A space is missing at the end of the expected result
+    expected = "TT\nhh\nee\n  \nff\noi\nuf\nrt\nth\nh \n l\nli\nin\nne\ne.\n. "
 
     assert_equal expected, Transpose.transpose(input)
   end
@@ -69,8 +70,11 @@ class TransposeTest < Minitest::Test
   def test_mixed_line_length
     skip
     input = "The longest line.\nA long line.\nA longer line.\nA line."
+    # The expected result is defined as "TAAA\nh   \nelll\n ooi\nlnnn\nogge\nn e.\nglr\nei \nsnl\ntei\n .n\nl e\ni .\nn\ne\n.",
+    # but the result should be
+    # "TAAA\nh   \nelll\n ooi\nlnnn\nogge\nn e.\nglr \nei  \nsnl \ntei \n .n \nl e \ni . \nn   \ne   \n.   "
 
-    expected = "TAAA\nh   \nelll\n ooi\nlnnn\nogge\nn e.\nglr\nei \nsnl\ntei\n .n\nl e\ni .\nn\ne\n."
+    expected = "TAAA\nh   \nelll\n ooi\nlnnn\nogge\nn e.\nglr \nei  \nsnl \ntei \n .n \nl e \ni . \nn   \ne   \n.   "
 
     assert_equal expected, Transpose.transpose(input)
   end
```

So we can see what the changes are in the message.

**Comment by kotp** [comment]
Thanks for reporting this.

**Comment by kotp** [comment]
Can you show your implementation?  I am finding that the changes to the tests causes the "golden copy" to fail, which means that the solution that we have for this fails this proposed test.

Also, what is the metric that determined that the tests were wrong?  Was it the README description?

**Comment by glennj** [comment]
I think you're misunderstanding the problem. The tests are fine.

I have this comment in my solution:
```ruby
  # Pad an array of lines such that each line
  # is at least as long as any following lines.
  #
  # example: ["foo", "bang", "barbaz", "qux"]
  # becomes: ["foo   ", "bang  ", "barbaz", "qux"]
  # because line 2 is longer
```

**Comment by matheusma37** [comment]
I made a mistake in my analysis. The README says that spaces should not be placed on the right side, but I got confused seeing other tests that had spaces on that side and I didn't realize that it was due to there being a space in that position in the string as well. I'm so sorry for that situation. After reevaluating I realized my mistake.

**Comment by kotp** [comment]
I can pick up mentoring for your iterations since you have our attention. ;)
