### ISSUE TITLE
GitHub Actions: Enable Window and macOS builds

### ISSUE THREAD

**Issue by kotp** [exercism/ruby#1050]
_Originally posted by @cmccandless in https://github.com/exercism/ruby/pull/1047#issuecomment-713622379_

**Comment by ErikSchierboom** [comment]
Basically, the following lines should be enabled https://github.com/exercism/ruby/blob/main/.github/workflows/exercise-tests.yml#L19-L20 and then the tests should pass. 

Side note: I'd prefer to use OS-specific versions, so `windows-2022` and `macos-11`.
See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by kotp** [comment]
Thank you @ErikSchierboom .  Now the question becomes, do we really need to have the other operating systems enabled?

**Comment by kotp** [comment]
Quick reference: #1047 and #1048

**Comment by ErikSchierboom** [comment]
> Now the question becomes, do we really need to have the other operating systems enabled?

🤷 I think it is quite important for all the exercises to work on all operating systems, so it depends a bit on what the risk is of things not working on different platforms. For example, for the C# track, I don't test against multiple OS'es, as I'm quite confident that everything will work cross-platform.

**Comment by kotp** [comment]
I am going to temper the "all operating systems" to mean Linux plus the two listed in the subject line.

I do not know any reason to test against any other operating system, mostly for the same reason.  Ruby MRI as a C language should be cross-platform (Linux, Mac, PC, and beyond) compatible, at least for the exercises we currently have.

So, for me, the answer is "No.".

I was hoping someone else would know if there is a reason to enable Windows and macOS (OS X), at the moment, or in the foreseeable future.

We currently are not suffering from it, from what I can see, and no reports that any of the exercises are causing platform dependent failures.

**Comment by kytrinyx** [comment]
My sense is also that we're going to generally be fine on Mac or Windows.

I think it's worth closing this as fixed, and reconsidering if we find that there are problems in the future on either Mac or Windows.

**Comment by kotp** [comment]
This should be closed automatically when #1447 is pulled in, as well.

**Comment by kotp** [comment]
@kytrinyx Any opinion on #1447 which was meant to close this?

**Comment by kytrinyx** [comment]
@kotp I didn't see that, as I wasn't tagged as a reviewer, and I wasn't monitoring the repo closely. I've approved it now.

In the future, if you'd like me to look at something, please tag me. I might see it if you don't, but I might not; it really depends on what I'm working on just then. If you tag me, I'll definitely see it, even if it takes a few days.

**Comment by kotp** [comment]
Yep, that is what I did this time, just waited a few days in case you saw it in passing or someone else did.
