### ISSUE TITLE
[V3] Boolean vs boolean

### ISSUE THREAD

**Issue by kotp** [exercism/ruby#1058]
exercism/v3#2281 has a discussion started about referencing "Boolean" and "boolean" and the problems that can be associated with using "boolean" and the formal `true` and `false` being listed when we don't really mean that as a requirement.

The comments came about from the issue above, while the details are found [here][here-1] and [here][here-2].

The Concept is "Boolean" and includes the less formal 'boolean' as well, for being subject complete.

Files effected:
- `./languages/ruby/exercises/concept/booleans/.docs/instructions.md`

Suggestion is to remove the true/false reference, or capitalize the B in `boolean`.

[here-1]: https://github.com/exercism/v3/pull/2281/files/1982965b2de6626a7aa329434198f31026bdbc8d#r499105549
[here-2]: https://github.com/exercism/v3/pull/2281/files/1982965b2de6626a7aa329434198f31026bdbc8d#r499105609

**Comment by kytrinyx** [comment]
It looks like this has been dealt with. I am going to close the issue.
