### ISSUE TITLE
[V3] Use consistent naming for method references

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/ruby#1060]
Looking at the existing Ruby exercises, there are a couple of different ways methods are referred to. I've seen:

- `'Please implement the pass? method'`
- 'Please implement the LogLineParser.log_level method'
- 'Please implement the Lasagna#remaining_minutes_in_oven method'

There are several places where methods are being referred to, but most notably they are referred to in the `instructions.md` files and the stub implementation files (and occasionally the `hints.md` files). It would be nice to use a uniform way of referring to methods.

I'm fairly sure that @iHiD wants to use `<CLASS>.<METHOD>` for class methods, and `<CLASS>#<METHOD>` for instance methods. So I'd suggest normalizing to those.

**Comment by kytrinyx** [comment]
This has been normalized. Closing.
