### ISSUE TITLE
[V3] Implement new Concept Exercise: inheritance

### ISSUE THREAD

**Issue by biancapower** [exercism/ruby#1064]
This issue describes how to implement the `inheritance` concept exercise for the Ruby track.

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before diving into the implementation, please read up on the following documents:

- [The features of v3](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md).
- [Rationale for v3](https://github.com/exercism/v3/blob/master/docs/rationale-for-v3.md).
- [What are concept exercise and how they are structured?](https://github.com/exercism/v3/blob/master/docs/features-of-v3.md)

Please also watch the following video:

- [The Anatomy of a Concept Exercise](https://www.youtube.com/watch?v=gkbBqd7hPrA).

## Goal

The goal of this exercise is to teach the student the Concept of Inheritance in Ruby.

## Learning objectives

- Know what inheritance is.
- Know how to inherit from a class.
- Know that all types inherit from object.

## Out of scope

N/A

## Concepts

- `inheritance`
- `objects`

## Prerequisites

- `classes`

Any data types used in this exercise (e.g. `strings`) should also be added as prerequisites.

### Hints

- [What is Inheritance in Ruby?](https://www.rubyguides.com/2019/01/what-is-inheritance-in-ruby/)

### After

- [Ruby Inheritance and Object Hierarchy](https://medium.com/@ensallee/ruby-inheritance-and-object-hierarchy-e0f908630fc7)
- [Ruby Docs on Inheritance](https://ruby-doc.org/docs/ruby-doc-bundle/UsersGuide/rg/inheritance.html)

## Representer

This exercise does not require any specific representation logic to be added to the [representer](https://github.com/exercism/ruby-representer).

## Analyzer

This exercise does not require any specific analyzer logic to be added to the [analyzer](https://github.com/exercism/ruby-analyzer).

## Implementing

To implement this exercise, please [follow these instructions](https://github.com/exercism/v3/blob/master/languages/ruby/reference/implementing-a-concept-exercise.md).

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by iHiD** [comment]
@biancapower I'd still love someone to do these. Any reason to close them?
