### ISSUE TITLE
[V3] Extract Concepts from v2 exercise Matrix

### ISSUE THREAD

**Issue by compostbrain** [exercism/ruby#1072]
Extract the list of concepts required to solve the v2 Ruby
exercise: `matrix`. For each concept, describe why it is required to
solve the exercise. Keep in mind that an exercise can have multiple
approaches. The goal of this task is to help determine the total list of
concepts that make up `matrix`.

The list of concepts should be stored in the following document:
`languages/Ruby/reference/exercise-concepts/matrix.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/Ruby/reference/exercise-concepts/matrix.md

**Comment by kytrinyx** [comment]
I've done a bit of a deep dive on the various processes that different tracks have followed when developing their syllabus, and one of the things that I learned is that trying to come up with a full list of concepts up front was less successful than we had hoped it would be.

In general the most successful approach seemed to use a "just in time" strategy, working from the root of the concept tree, identifying a small handful of concepts that were not too far ahead in the tree, and then filling gaps where necessary.

I'm going to go ahead and close this issue. If someone wants to work on concept exercises, please open an issue and we can  help identify a good concept to tackle, as well as provide some guidance on how to proceed from there.
