### ISSUE TITLE
Incomplete coverage in Word Count tests; solutions proposed

### ISSUE THREAD

**Issue by MpdWalsh** [exercism/ruby#1086]
(I want to preface this by saying that I know these are just simple exercises to get people learning a language and the tests aren't meant to cover every possible scenario that one might encounter.)

I just finished the Word Count exercise and skimmed through other folks' solutions. I noticed a regex in a number of solutions that works with the existing test suite, but would miss plural possessive nouns (eg. folks') and leading apostrophes (eg. '90s).

This expression, as I understand it, makes sure a word starts an alphanumeric character, then uses a non-capturing group to ensure any apostrophes are followed by an alphanumeric character: `/\w+(?:'\w+)*/`

For leading apostrophes, I propose adding a test like this:

```
def test_leading_apostrophe
  skip
  phrase = Phrase.new("Life was easier in the '90s.")
  counts = {"life"=>1, "was"=>1, "easier"=>1, "in"=>1, "the"=>1, "'90s"=>1}
  assert_equal counts, phrase.word_count
end
```

And since plural possessives may end with just the apostrophe, I propose adding this test (or something similar):

```
def test_plural_possessive_noun
  skip
  phrase = Phrase.new("Programmers of tests don't care about other programmers' feelings.")
  counts = {"programmers"=>1, "of"=>1, "tests"=>1, "don't"=>1, "care"=>1, "about"=>1, "other"=>1, "programmers'"=>1, "feelings"=>1}
  assert_equal counts, phrase.word_count
end
```

**Comment by kotp** [comment]
@MpdWalsh This could be something added to the mentor notes as well, to explore regular expressions.

This kind of problem/solution might be suited to a concept exercise related to Regular Expressions as well.

**Comment by kytrinyx** [comment]
I believe we now have a much more robust coverage of apostrophe cases in this exercise.

If this is not so, please open an issue in problem-specifications to discuss adding more cases to the shared (language-agnostic) problem metadata described here: https://github.com/exercism/problem-specifications/blob/main/exercises/word-count/canonical-data.json
