### ISSUE TITLE
[WIP] Concept Exercises Overview

### ISSUE THREAD

**Issue by iHiD** [exercism/ruby#1123]
This is a WIP list of all of the Concept Exercises, remaining tasks, and their states for v3.

## iHiD has checked them but then need a final proofing
- `lasagna`
- `amusement-park`
- `amusement-park-improvements`
- `log-line-parser`
- `assembly-line`
- `savings-account`
- `bird-count`

**Comment by kytrinyx** [comment]
These have been in production for a while; closing this issue.
