### ISSUE TITLE
Incorrect use of NotImplementedError

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/ruby#1151]
A lot of the files in this repo contain raising an `NotImplementedError` as shown [here](https://github.com/exercism/ruby/search?q=NotImplementedError).

`NotImplementedError` in Ruby is **not** the same as .NET's `NotImplementedException` or Java's `UnsupportedOperationException`.

Ruby's error is only meant to be used for unimplemented p/invokes, as written in the official documentation:

> Raised when a feature is not implemented on the current platform. For example, methods depending on the `fsync` or `fork` system calls may raise this exception if the underlying operating system or Ruby runtime does not support them.
> 
> Note that if fork raises a `NotImplementedError`, then `respond_to?(:fork)` returns false.

If raising errors stays (see [discussion on slack](https://exercism-team.slack.com/archives/CR91YFNG3/p1625580325431300)), it should not be this.

**Comment by kotp** [comment]
"See discusson on slack" doesn't take me to where this was discussed.  Please link the discussion @SleeplessByte

**Comment by kotp** [comment]
Perhaps the example is an example, but not fully documented?  Since it is the inherited by `ScriptError` the use does not seem contraindicated.  The documentation may be incomplete instead, as is the case with quite a bit of Ruby documentation  (this has improved quite a bit over the last decade though).

We are using the exception to indicate that there is an error in the script, that we expect the implementation of this behavior.

**Comment by kotp** [comment]
It also has the side effect of providing a negative response when asked if something `responds_to?` that method.  This ability would be lost if we used something else, since (if I remember correctly) it is hooked into that mechanism.

**Comment by SleeplessByte** [comment]
> It also has the side effect of providing a negative response when asked if something responds_to? that method. This ability would be lost if we used something else, since (if I remember correctly) it is hooked into that mechanism.

That's `NoMethodError`, I think.

**Comment by kotp** [comment]
Currently, there are no codes that use this, but there are three files that are markdown that references `raise NotImplementedError`.  Now it seems strange that this specific error is raised, as opposed to talking about `StandardError` and its role in Ruby.

**Comment by kotp** [comment]
I think my point is that perhaps we shouldn't define the method at all.  I understand "scaffolding" for the student, but the tests should be informing the student that a method does not exist already, when it doesn't exist.  So we are "making work" where work probably could be not done and the communication of `NoMethodError` being raised does its job in Ruby.

This might mean, if we do want to supply some scaffolding:

1. We make a comment with the name
2. We make the method for the student, we leave it empty
  - This would not inherently raise an error, but would fail the tests
  - This may raise errors relating to `nil` which may be more confusing to the student
3. We create a custom exception class that is created in the test file that might be called `StudentMustImplementError` with a helpful message mirroring the needful.

I kind of prefer the third option.  It is explicit, informative as we need it to be.  Raising a runtime error for the sake of raising a runtime error means that if the student needs to rescue for some reason, they aren't allowed to by our design.  Creating a custom exception, they can raise that explicitly if they need or want to.
3.

**Comment by kotp** [comment]
This looks like it has been resolved, tending to use `NoMethodError` rather than a custom exception.

**Comment by kotp** [comment]
And thanks @SleeplessByte
