### ISSUE TITLE
Check docs are up to date

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/ruby#1172]
Please check if your documentation files are still up-to-date.

The key documentation files to check are:

- `docs/ABOUT.md`
- `docs/INSTALLATION.md`
- `docs/LEARNING.md`
- `docs/RESOURCES.md`
- `docs/TESTS.md`
- `exercises/shared/.docs/help.md`
- `exercises/shared/.docs/tests.md`

There might be more.

## Link check report

To help identify invalid links, we've automatically checked the links of _all_ `*.md` files in this repo.
This is the report of that check:

<pre style="color:#bbb;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word">📝 Summary
---------------------
🔍 Total..........203
✅ Successful.....200
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........3

Errors in ./exercises/concept/lasagna/.docs/hints.md
<span style="color:#ff5555">✗ https://launchschool.com/books/ruby/read/methods (HTTP status client error (404 Not Found) for url (https://launchschool.com/books/ruby/read/methods))</span>

Errors in ./README.md
<span style="color:#ff5555">✗ https://github.com/YOUR-USERNAME/YOUR-RUBY-REPOSITORY (404 Not Found: Not Found)</span>
<span style="color:#ff5555">✗ https://github.com/YOUR-USERNAME/YOUR-PROBLEM-S-REPOSITORY (404 Not Found: Not Found)</span>

</pre>
## Tracking

https://github.com/exercism/v3-launch/issues/54

**Comment by americodls** [comment]
@ErikSchierboom If I understood correctly this is not an issue (at least not anymore).

👇🏼   This page is not returning 404 anymore. It is working fine.
> Errors in ./exercises/concept/lasagna/.docs/hints.md
> ✗ https://launchschool.com/books/ruby/read/methods (HTTP status client error (404 Not Found) for url (https://launchschool.com/books/ruby/read/methods))

👇🏼   I believe these links should not be even tested (they are only examples).
> Errors in ./README.md
> ✗ https://github.com/YOUR-USERNAME/YOUR-RUBY-REPOSITORY (404 Not Found: Not Found)
> ✗ https://github.com/YOUR-USERNAME/YOUR-PROBLEM-S-REPOSITORY (404 Not Found: Not Found)

If there is something I should do here, let me know.

**Comment by ErikSchierboom** [comment]
Yep, this can be closed.
