### ISSUE TITLE
Add missing files for advanced-enumeration concept

### ISSUE THREAD

**Issue by iHiD** [exercism/ruby#1177]
@ErikSchierboom @angelikatyborska @neenjaw The files for the `advanced-enumeration` concept are missing, which is going to cause a sync failure. If any of you have 15mins to put them together, that'd be great. You can copy the second of the boutique exercise intro as a stub for the intro + about. Otherwise I'll try and get to it soon!

**Comment by angelikatyborska** [comment]
I'm on it

**Comment by iHiD** [comment]
Thank you! 💙
