### ISSUE TITLE
Add `debug.md` to explain how to debug in the web editor

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/ruby#1195]
In https://github.com/exercism/ruby-test-runner/commit/a215353f4c0892a8d104153003eb6ed383a40928 a custom `debug` function was added to allow students to capture output during test runs. Other printing methods like `puts` won't work.

This needs to be documented in `exercises/shared/debug.md` (see https://github.com/exercism/docs/blob/main/building/tracks/shared-files.md#file-debugmd)

**Comment by kytrinyx** [comment]
This has been moved to `exercises/shared/.docs/debug.md`
