### ISSUE TITLE
Unit tests (in Savings Account) use assert_equal

### ISSUE THREAD

**Issue by paulvt** [exercism/ruby#1199]
The unit tests in the Savings Account exercise tests equivalence of floats using `assert_equal` instead of `assert_in_delta` (as is suggested by the Minitest docs).
I am doing this track as a seasoned Ruby developer so I can start mentoring the track once I know the exercises but I got stuck here.

The annual balance update in this exercise can be calculated via:
```ruby
balance + (balance * rate.abs / 100.0)
```
Which, on my machine, for the test on `SavingsAccountTest#test_annual_balance_update_for_large_positive_start_balance` results in the expected `1016.2101016209999`.
However, if you do this slightly different, but mathematically the same:
```ruby
balance * (1.0 + rate.abs / 100.0)
```
It results in `1016.210101621` which then gets rejected by the test although it is obviously correct and even more precise!
The test relies on too specific float rounding here IMO, which a test should never do.

**Comment by SleeplessByte** [comment]
@paulvt je hebt gelijk! 

If you have time, can you submit a PR?

**Comment by kotp** [comment]
I noticed the same thing as I was reviewing this late last night as well, delta would definitely be appreciated.

**Comment by paulvt** [comment]
I will have a look this week.

**Comment by Steffan153** [comment]
This should be closed now.

**Comment by kotp** [comment]
Thanks @Steffan153 .
