### ISSUE TITLE
Practice exercises example solutions do not follow file structure/naming standard

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [exercism/ruby#1205]
Practice exercises’ example solution files do not follow the structure/naming specified in https://exercism.org/docs/building/tracks/practice-exercises

The docs use the `.meta/example.rb` (or `exemplar.rb`if it is a concept exercise) naming convention but the practice exercises use `.meta/solutions/exercise_name.rb`

(The test suite only covers practice tests, not concept exercises. I'd like to try to extend the test system to include concept exercises, but I'd rather wait until the practice exercises are updated).

**Comment by angelikatyborska** [comment]
Changing the location of the example solutions for practice exercises should be easy to automate with a script. It just needs to move the files and then update the `config.json` files with new paths. But before we attempt this we would need @iHiD to confirm if he even wants the change in the Ruby track?

**Comment by ntijoh-daniel-berg** [comment]
Seems like I never got notified of the previous comment, so I did not wait.
Was a learning experience even if it never gets used.
