### ISSUE TITLE
Concepts used in practice exercises missing from concepts exercises

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [exercism/ruby#1218]
Running configlet produces the following warnings:

> The following concepts exist in the `practices` array of a Practice Exercise in `/Users/daniel.berg/Documents/Projekt/Exercism/ruby/config.json`, but do not exist in the top-level `concepts` array
regular-expressions
ordering
classes
hashes
casting
sets
equality
time
math-operators
enumerable
recursion
integral-numbers
constructors
lambdas
higher-order-functions
lazy-evaluation
stacks
bit-manipulation
symbols
parameters
randomness
queues
immutability
structs
dates

> The following concepts exist in the `prerequisites` array of a Practice Exercise in `/Users/daniel.berg/Documents/Projekt/Exercism/ruby/config.json`, but are not in the `concepts` array of any user-facing Concept Exercise
constructors
ordering
classes
hashes
casting
equality
time
integers
math-operators
enumerable
integral-numbers
generic-methods
lambdas
higher-order-functions
symbols
lazy-evaluation
stacks
bit-manipulation
parameters
randomness
queues
immutability
sets
structs
dates

> The following concepts exist in the `prerequisites` array of a Practice Exercise in `/Users/daniel.berg/Documents/Projekt/Exercism/ruby/config.json`, but do not exist in the top-level `concepts` array
constructors
ordering
classes
hashes
casting
equality
time
integers
math-operators
enumerable
integral-numbers
generic-methods
lambdas
higher-order-functions
symbols
lazy-evaluation
stacks
bit-manipulation
parameters
randomness
queues
immutability
sets
structs
dates

It also says:
> These warnings will become errors in a future configlet release (at the end of October 2021).
For more information, please see the documentation: https://github.com/exercism/docs/blob/main/building/configlet/lint.md

**Comment by kytrinyx** [comment]
@ErikSchierboom Is this a problem that other tracks have solved?

My immediate thought is that we can add a new key to the hash that configlet ignores, and move the unimplemented concepts into it. E.g.

```json
      {
        "slug": "connect",
        "name": "Connect",
        "uuid": "538a6768-bae5-437c-9cdf-765d73a79643",
        "practices": [
        ],
        "prerequisites": [
          "strings",
          "arrays",
          "conditionals"
        ],
        "todo": {
          "practices": [
          ],
          "prerequisites": [
            "symbols"
          ],
        },
        "difficulty": 9
      },
```

Thoughts?

**Comment by ErikSchierboom** [comment]
>  Is this a problem that other tracks have solved?

Well, the only way you _can_ solve this is by either creating the stubs for the concepts or removing the missing concepts. I'd be fine with either approach. It might be enough to remove them here and store them in an issue, to not lose the data. The custom key could also work (as configlet doesn't yet touch the config.json file).

**Comment by kytrinyx** [comment]
Storing them in an issue is not a bad idea, either. Ok, cool. Let me think about it for a bit and I'll fix it one way or the other.
