### ISSUE TITLE
Pangram test cases fail on Submit but succeed locally

### ISSUE THREAD

**Issue by sanevillain** [exercism/ruby#1220]
Just wanted to bring this to your attention as my solution to the Pangram exercise passes all local tests but fails to do so when I submit it to the website. 

I tried running the suite on two different versions `2.6.3` and `2.7.0` but the outcome was the same

**Comment by kotp** [comment]
Is it this code and this message?

![image](https://user-images.githubusercontent.com/16747/133594229-c91cac8d-f749-439d-bd11-d56ea019a60f.png)

**Comment by sanevillain** [comment]
Yes it is

**Comment by kotp** [comment]
It is reporting that the tests are passing when I look at the exercise here: https://exercism.org/tracks/ruby/exercises/pangram/solutions/sanevillain

Is that the code exactly?

```ruby
class Pangram
  ALPHABET = ('a'..'z').to_a
  def self.pangram?(sentence)
    (ALPHABET & sentence.downcase.chars).length == 26
  end
end
```

Sorry for any missing vertical whitespace, it does not copy well from the GUI browser.

(I would also say that you do not need to coerce the range to an array, both are "enumerable".)

If this is the correct code, can you replace the set intersection operator with `uniq` method call and see if the same error happens?

**Comment by sanevillain** [comment]
seems like it's passing now

**Comment by kotp** [comment]
Thanks for reporting back.
