### ISSUE TITLE
Ruby Basics Introduction.md typo

### ISSUE THREAD

**Issue by participator** [exercism/ruby#1230]
[Ruby About Basics](https://github.com/exercism/ruby/blob/main/concepts/basics/introduction.md)
The named parameter, num2, is typed as num_2 when the function is called.

<img width="570" alt="Ruby Basics Misspelled Name Parameter" src="https://user-images.githubusercontent.com/7463405/134282539-a6d11e52-5a08-40ed-be8e-9c068ab2de38.png">

**Comment by angelikatyborska** [comment]
Thanks for reporting! Would you be interested in submitting a PR with a fix?

The same problem appears in two different files:
- https://github.com/exercism/ruby/blob/main/exercises/concept/lasagna/.docs/introduction.md
- https://github.com/exercism/ruby/blob/main/concepts/basics/introduction.md

**Comment by participator** [comment]
Yes, I am.  I can submit it by the end of day today.

**Comment by participator** [comment]
Updated!

**Comment by tejasbubane** [comment]
The PR is merged so I think this issue can be closed now.
