### ISSUE TITLE
Non-determenistic last test case for Robot Name

### ISSUE THREAD

**Issue by sanevillain** [exercism/ruby#1240]
```
  def test_generate_all_robots
    all_names_count = 26 * 26 * 1000
    time_limit = Time.now + 60 # seconds
    seen_names = Hash.new(0)
    robots = []
    while seen_names.size < all_names_count && Time.now < time_limit
      robot = Robot.new
      seen_names[robot.name] += 1
      robots << robot
    end
    assert_equal all_names_count, robots.size, timeout_message
  end
```

I believe that the `while` loop here leads to non-deterministic behavior. The amount of robots generated is almost always different than the expected number because the loop uses the length of the `seen_names` keys and fails to take into consideration the total number of times a name was created

**Comment by kotp** [comment]
The seen names will never include duplicates, so this should be deterministic. The number of times the same name is created should be immaterial (and discarded).

Is this causing an intermittent failure for your solution?

**Comment by kotp** [comment]
The test does seem strange though, because there should be only unique robot names (I will read the description, I have not looked at it for years.)

**Comment by SleeplessByte** [comment]
This test looks correct to me. The number of names will be different if the code fails to generate all names within 60 seconds.

**Comment by kotp** [comment]
That is what I am seeing too @SleeplessByte .  I am going to close it.

@sanevillain can comment still though.  Let us know what the doubts are, and a test to maybe prove the issue, if you can.

**Comment by sanevillain** [comment]
Okay. This is super weird. Yesterday the problem for me with this last test case was that on every run a different number of robots was created and that number was unpredictable. What I mean by that is that the number of unique names that the `while` loop depends on can't be exceeded since they are used as hash keys in the condition and the number of times any given name could've been added is saved but not used. So all in all I was creating more robots in the given time than the total number of unique names.

However, today this last test case passes without a problem. I haven't changed my solution, but for some reason, it's passing every time I run it. I uploaded my solution again, but it seems to be failing on the website now. Will appreciate it if you can tell me if it's something in my code that leads to this weird behaviour

```
class Robot
  @@NAMES = []

  attr_reader :name

  def initialize
    self.class.generate_names if @@NAMES.empty?
    reset
  end

  def reset
    @name = @@NAMES.pop
  end

  class << self
    def forget
      @@NAMES = []
    end

    def generate_names
      ('A'..'Z').each do |a|
        ('A'..'Z').each do |b|
          (0...10).each do |c|
            (0...10).each do |d|
              (0...10).each do |e|
                @@NAMES << "#{a}#{b}#{c}#{d}#{e}"
              end
            end
          end
        end
      end

      @@NAMES.shuffle!
    end
  end
e
```

**Comment by SleeplessByte** [comment]
This solution looks like it would work (albeit the `reset` name being not optimal in mu opinion), without anything that's particularly causing different runs to have different results.

**Comment by sanevillain** [comment]
I really don't understand how this issue is already closed when every correct solution that passes the test locally times out once uploaded to the platform. (Including the example solution to the problem)

**Comment by kotp** [comment]
I closed it because the title of the problem states that it is non-deterministic last test case.  I believed that you indicated this is not the case.

Would you want to change the title of the issue to match the problem that you are seeing, and perhaps reopen and comment?

![image](https://user-images.githubusercontent.com/16747/136063903-aef42306-238a-4610-8eff-304522d228b8.png)

If this is the message that we get every time, then we have a different issue, I think.

Can you make the adjustments that you think are needed for this issue, if it is no longer a "non-deterministic last test" and a timing problem perhaps on the server.  Then we can move this issue to the test runner repository and address it there.

**Comment by sanevillain** [comment]
I agree that this issue has to be moved to the test runner repository. I changed the title, but don't really know how to contribute more to it as I can't see anything more than the `an error occurred` or `your tests timed out` message from the test runner

**Comment by kotp** [comment]
That is excellent.  Thank you @sanevillain .
