### ISSUE TITLE
Zipper needs a test for .up.up

### ISSUE THREAD

**Issue by moveson** [exercism/ruby#1260]
As currently written, the Ruby Zipper test suite doesn't test a key feature of the zipper structure, which is the ability to navigate all the way back to the top of the tree from any depth. I recently completed this exercise, and my first iteration passed all tests even though it did not properly implement this feature.

**Comment by kotp** [comment]
For reference, the description of the exercise is [here](https://github.com/exercism/ruby/blob/main/exercises/practice/zipper/.docs/instructions.md) as implemented currently, with [problem-specifications](https://github.com/exercism/problem-specifications/blob/main/exercises/zipper/description.md).

We would need to open an issue there if we want the additional specification added, as it is probably applicable for other tracks, while if we add it "ruby track only" we would track adjustments.

**Comment by kotp** [comment]
If you do want to pursue this, I think the next step is to open (search
first) an issue at [problem-specifications][1] and get consensus from
other tracks that utilize this exercise on the wanted change, and in the
meantime, Ruby can test for this, if you want to create a pull request
in this repository.

[1]: https://github.com/exercism/problem-specifications/issues/

**Comment by kotp** [comment]
It is applied for the Ruby track, and the work is started on Problem Specifications via the open issue!

Thank you @moveson for the contribution to the exercise on this track!
