### ISSUE TITLE
Pre-requisite and missing hints for Simple Calculator

### ISSUE THREAD

**Issue by solumna** [exercism/ruby#1305]
Hello,

I found some issues when doing the simple calculator excercise, which is :
1. The hints are not yet implemented
2. To complete the exercise, user need to use conditional concept such as "if-else". As for now the simple-calculator exercise which is in the "Raising Exception" concept is unlocked after completing basics.

**Comment by iHiD** [comment]
Yeah, conditionals should be added as a prereq. Feel free to PR it :)

**Comment by NeimadTL** [comment]
Hi everyone, here's a PR for it #1331.

**Comment by kotp** [comment]
Closed via #1331
