### ISSUE TITLE
stock_for_item method in boutique Inventory challenge

### ISSUE THREAD

**Issue by tundeiness** [exercism/ruby#1308]
The **stock_for_item** method in the Boutique Inventory challenge looks like this before implementation:
```
def stock_for_item(name) 
end
```
After several iterations, I found out that there is no need for the `name` argument in the `stock_for_item` method because I could solve the challenge without supplying the `name` argument and it could be solved like below:

```
def stock_for_item(name)
    items[0][:quantity_by_size]
end
```
`items` being an instance variable.

So it got me suspecting that maybe the instructions are not being enforced by the tests or something else that I may not know.

**Comment by tundeiness** [comment]
Also, removing `name` from the stock_for_item methods throws an error making the test not pass.

**Comment by kotp** [comment]
The removal of `name` from the method is enforced by the tests, so that is not surprising.

The instructions state this:

    ## 4. Return a single item's stock
    
    I'mplement `BoutiqueInventory.stock_for_item(name)` to return the stock of an item by its name:
    
    ```ruby
    BoutiqueInventory.new([
      {price: 65.00, name: "Maxi Brown Dress", quantity_by_size: {s: 3, m: 7, l: 8, xl: 4}},
      {price: 50.00, name: "Red Short Skirt", quantity_by_size: {}},
      {price: 29.99, name: "Black Short Skirt", quantity_by_size: {s: 1, xl: 4}},
      {price: 20.00, name: "Bamboo Socks Cats", quantity_by_size: {s: 7, m: 2}}
    ]).stock_for_item("Black Short Skirt")
    
    #=> {s: 1, xl: 4}
    ```

And the example is good, but unfortunately it only tests the first position, so if the student solution is only checking for the first entry, then it will pass.

This suggests, then, that we need a second test, with an item that is selected by name in a position other than the first position.

Are you up for a patch for this?

**Comment by tundeiness** [comment]
yes, I hope the timing will be right?
-------- Original message --------From: Victor Goff ***@***.***> Date: 02/04/2022  09:36  (GMT+01:00) To: exercism/ruby ***@***.***> Cc: Tunde Oretade ***@***.***>, Author ***@***.***> Subject: Re: [exercism/ruby] stock_for_item method in boutique Inventory challenge (Issue #1308) 
The removal of name from the method is enforced by the tests, so that is not surprising.
The instructions state this:
## 4. Return a single item's stock

I'mplement `BoutiqueInventory.stock_for_item(name)` to return the stock of an item by its name:

```ruby
BoutiqueInventory.new([
  {price: 65.00, name: "Maxi Brown Dress", quantity_by_size: {s: 3, m: 7, l: 8, xl: 4}},
  {price: 50.00, name: "Red Short Skirt", quantity_by_size: {}},
  {price: 29.99, name: "Black Short Skirt", quantity_by_size: {s: 1, xl: 4}},
  {price: 20.00, name: "Bamboo Socks Cats", quantity_by_size: {s: 7, m: 2}}
]).stock_for_item("Black Short Skirt")

#=> {s: 1, xl: 4}
```

And the example is good, but unfortunately it only tests the first position, so if the student solution is only checking for the first entry, then it will pass.
This suggests, then, that we need a second test, with an item that is selected by name in a position other than the first position.
Are you up for a patch for this?

**Comment by kotp** [comment]
We got it set up, now tomorrow hopefully you can get the PR created.

**Comment by tundeiness** [comment]
Hi Victor,I just checked the open office now to see if you are there. Maybe we can meet tomorrow?
    On Saturday, 2 April 2022, 20:19:57 GMT+1, Victor Goff ***@***.***> wrote:  
 
 


We got it set up, now tomorrow hopefully you can get the PR created.
