### ISSUE TITLE
`item_names` in Boutique Inventory challenge

### ISSUE THREAD

**Issue by robsdudeson** [exercism/ruby#1315]
The instructions indicate that `item_names` should only [consider items with stock](https://github.com/exercism/ruby/blob/0ccfe9c9e85eca433e23a9bcdf2227dd714b1596/exercises/concept/boutique-inventory/.docs/instructions.md?plain=1#L18) but the [tests expect names of items without stock to be in the output](https://github.com/exercism/ruby/blob/0ccfe9c9e85eca433e23a9bcdf2227dd714b1596/exercises/concept/boutique-inventory/boutique_inventory_test.rb#L9)

**Comment by kotp** [comment]
Yep, I did mention this in the related #1316.  I think we clarify the README, and maybe add a test that gathers information about stock levels that are low (whatever that level may be at the moment called).  But we should also make sure that we are sticking to the concepts that are given for this concept exercise.
