### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by vcborsolan** [exercism/ruby#1351]
Hello folks, I'm opening this issue to discuss if this repository will participate in the 2022 digital ocean [hacktoberfest](https://hacktoberfest.com/participation/#maintainers).

If so, let's review the issues and add the labels/tags for valid contributions.

**Comment by kotp** [comment]
The labels should already be in place.

Also, feel free to review the [issues], unless you are talking about other issues, then please elaborate.

[issues]: https://github.com/exercism/ruby/issues

**Comment by iHiD** [comment]
As a rule, Exercism doesn't generally participate in Hacktober fest as it creates more work for maintainers than it creates value for Exercism. If you create PRs that are in line with the repo (ie work on existing issues etc) then we maybe tag them as hacktoberfest-accepted (or whatever the label is nowadays) but unsolicited minor PRs will normally be tagged as `invalid`. We don't active react out for support so don't had labels to existing issues.

Thanks for checking.
