### ISSUE TITLE
 Binary Search Ruby

### ISSUE THREAD

**Issue by meatball133** [exercism/ruby#1391]
I am trying to finish the exercises with the following code:

```ruby
class BinarySearch
  def initialize(input)
    @input = input
  end

  attr_reader :input
  
  def search_for(input2)
      i = input.length -1
      j = 0
      n = (i + j)/2
      while i - j == 1
        if input2 == input[n]
          return n
        elsif n == 1
          return nil
        elsif input2 > input[n]
          j = n +1
        else
          i = n -1
        end
      n = (i + j)/2
      end
  end
end
```
Although I get the following error:
"ArgumentError: wrong number of arguments (given 1, expected 0)

Traceback (most recent call first):
    Line 16:in `length'
    Line 16:in `search_for"
  
  Although If I change it to this:
```ruby
  class BinarySearch
  def initialize(input)
    @input = input
  end

  attr_reader :input
  
  def search_for(input2,input3)
      i = input.length -1
      j = 0
      n = (i + j)/2
      while i - j == 1
        if input2 == input[n]
          return n
        elsif n == 1
          return nil
        elsif input2 > input[n]
          j = n +1
        else
          i = n -1
        end
      n = (i + j)/2
      end
  end
end
```
I get the following error:
"ArgumentError: wrong number of arguments (given 1, expected 2)

Traceback (most recent call first):
    Line 15:in `search_for'"
I would guess this is some error

**Comment by kotp** [comment]
You can submit this for mentoring, if you submit it using the CLI tool.  `exercism submit binary_search.rb` but I can tell you that the tests will give one value for `search_for` while this code is asking for 2 values.

The first test will confirm this:

```ruby
  def test_finds_a_value_in_an_array_with_one_element
    # skip
    binary = BinarySearch.new([6])
    assert_equal 0, binary.search_for(6)
  end
```

Your guess is correct, that this is some error.  Specifically `ArgumentError`.

**Comment by kotp** [comment]
Also look at the difference between unary `-` verses `-` used for subtraction, and the same for unary `+`.  In other words, be aware that `-1` and `- 1` are different from each other.

**Comment by kotp** [comment]
Closing this, after five days and no response, and the end of the weekend being upon us.  Feel free to give more information if you are not set, @meatball133 .
