### ISSUE TITLE
Question about function name in "Moviegoer" exercism

### ISSUE THREAD

**Issue by fhightower** [exercism/ruby#1464]
Hello! Why does the name of the [`claim_free_popcorn!` method](https://github.com/exercism/ruby/blob/987a1e8e87367dca1bcd7aaf57575358e76f7f42/exercises/concept/moviegoer/moviegoer.rb#L20) end with `!`?

I was reading through the [ruby style guide](https://github.com/rubocop/ruby-style-guide#dangerous-method-bang) and it sounds like methods ending with `!` are dangerous in some way (often modifying data or arguments in some way). From what I can see, there is nothing in the [`claim_free_popcorn!` method](https://github.com/exercism/ruby/blob/987a1e8e87367dca1bcd7aaf57575358e76f7f42/exercises/concept/moviegoer/moviegoer.rb#L20) that would classify it as a dangerous method.

Thanks for any input on the subject.

**Comment by iHiD** [comment]
@fhightower Hey! Could you repost this on [the Forum](https://forum.exercism.org/latest) please and I'll happily answer there! :)

**Comment by fhightower** [comment]
[Done](https://forum.exercism.org/t/question-about-claim-free-popcorn-function-name-in-moviegoer-exercism/981), thanks!
