### ISSUE TITLE
Typo in locomotive_engineer instrucions

### ISSUE THREAD

**Issue by carmemias** [exercism/ruby#1492]
Hello there,
There is a small typo in the instructions of the locomotive_engineer concept exercise.
Where it reads ["Create an list of all wagons"](https://github.com/exercism/ruby/blob/main/exercises/concept/locomotive-engineer/.docs/instructions.md#1-create-an-list-of-all-wagons), it should say "Create a list of all wagons".

**Comment by Benyam12** [comment]
o تأسف انگیز است برای ورود به حساب اصلی خودت ، که گویا اشتباها گزینه‌ای را فعال کرده‌ای ، با وجود اینکه تمام اطلاعات تکمیلی را طبق درخواست‌های گوگل  ، صحیح وارد می‌کنی و همچنان نمی توانی وارد شوید ...

واقعا متاسفم .
