### ISSUE TITLE
The Symbols document contains a factual error.

### ISSUE THREAD

**Issue by SoldierCoder** [exercism/ruby#1582]
In the Conversions section of the doc on Symbols it says:

To present a symbol as a string, you can use the String#to_sym method, 

and to do the opposite, you can use the Symbol#to_s method.

These are exactly reversed.  That is, to present a symbol, :hello, as a string, "hello" you can use the Symbol#to_s method,
and to do the opposite, you can use the String#to_sym method.

**Comment by kotp** [comment]
@SoldierCoder are you up for a patch for this?  I can reopen it.
