### ISSUE TITLE
Should the Attendee query methods end in a question mark?

### ISSUE THREAD

**Issue by larister** [exercism/ruby#1609]
Hi! Loving the Ruby course so far but I had a quick question:

In the [Introduction to the exercise](https://github.com/exercism/ruby/blob/main/exercises/concept/amusement-park/.docs/introduction.md), the author states that methods which get values (i.e. query methods) should end with a question mark - see the suitcase example.

However, in the [attendee.rb file](https://github.com/exercism/ruby/blob/main/exercises/concept/amusement-park/attendee.rb), neither the `height` nor the `pass_id` getters follow this convention. I'm new to Ruby so unsure of the answer, but I hope it's ok to ask here.

**Comment by kotp** [comment]
https://forum.exercism.org/t/should-the-attendee-query-methods-end-in-a-question-mark/8779/4 is the link to the discussion on the forums.
