### ISSUE TITLE
Issue with savings_account interest_rate test

### ISSUE THREAD

**Issue by principlebrothers** [exercism/ruby#1610]
## Problems
- The current test for `SavingsAccount.interest_rate ` is written to expect a fixed value of **0.5** for balances less than 1000. This contradicts the exercise specification which emphasizes an interest rate of **0.5% ~ 0.005**.

## Posible solution
- Kindly change the expected value to **0.5% ~ 0.005** of the balance for balances less than 1000.

Thank you

**Comment by kotp** [comment]
https://forum.exercism.org/t/issue-with-savings-account-interest-rate-test/8763 is the discussion link on the forums.
