### ISSUE TITLE
Correction: Conditional concept document introduction.md

### ISSUE THREAD

**Issue by swati-goyal** [exercism/ruby#1693]
## Else statement

The `else` statement can be used in conjunction with the `if` and `unless` statements.
The `else` statement will be executed if the `if` branch or the `unless` branch is not executed.

```ruby
value = 1
if value == 1
  "1 is equal to 1"
else
  "1 is not equal to 1"
end
# => "1 is equal to 1"

unless value < 2
  "1 is not greater than 2"
end
# => "1 is greater than 2" 
```

--
Change to below , because unless is executed when condition is falsey
```
unless value < 2
  "1 is not greater than 2"
end
# => nil

```

**Comment by kotp** [comment]
Related to issue #1688 but being discussed [here](https://forum.exercism.org/t/include-example-for-unless-statement/11667)
