### ISSUE TITLE
[Update config.json] Add values for topics and difficulty keys

### ISSUE THREAD

**Issue by Roshanjossey** [exercism/ruby#481]
Currently we have difficulty as 1 and topics as empty list for all exercises. We should update them to have relevant data.
Other language streams have used scripts to do this at once. For example https://github.com/exercism/xswift/pull/186
I believe this is something that this should evolve by everybody editing and adding their thoughts

**Comment by vinmaster** [comment]
Hi, I am new to this project. Can someone explain what the keys in config.json mean? e.g. Core and unlocked_by.

Also what kind of format should the topics be in? e.g. "Data Structure" or "data-structure"

**Comment by Insti** [comment]
This is a good place to start: https://github.com/exercism/ruby/pull/689

> We will be moving to a tree-shaped track rather than a linear one

Topics should be in snake case, so "data_structure". 
A list of generally agreed topics can be found in the problem-specifications repository: https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt

**Comment by Insti** [comment]
See https://v2.exercism.io for a preview of the new site/structure.
