### ISSUE TITLE
All Your Base driven deprecations

### ISSUE THREAD

**Issue by kotp** [exercism/ruby#501]
Deprecate the following exercises:

* [ ] Binary
* [ ] Trinary
* [ ] Hexidecimal
* [ ] Octal

re: exercism/x-common#279

**Comment by kotp** [comment]
This still needs to happen.

**Comment by F3PiX** [comment]
Those are marked deprecated in config.json.
Also, Alphametics is active. 

So, @kotp, can we close?

**Comment by kotp** [comment]
I believe so... 
/close
