### ISSUE TITLE
Generator: Add preamble method.

### ISSUE THREAD

**Issue by Insti** [exercism/ruby#589]
Add a method to the `ExerciseCases` class that can be overridden to provide common setup code when using the default template.

Ref:
 https://github.com/exercism/xruby/pull/583/files#r114226935 <- This should not require a custom template.

**Comment by hilary** [comment]
I believe there's at least one more exercise (bowling, I think) that would benefit from such a method. 

My guiding principle on these has been to wait until I have more than one use for such a method before adding it to `ExerciseCases`.
