### ISSUE TITLE
generator: replace --freeze with --update

### ISSUE THREAD

**Issue by hilary** [exercism/ruby#631]
(@Insti please fill in as you wish)

There's a long history to how we ended up with `bin/generate` defaulting to updating the xruby version of an exercise, with a `--freeze` option to prevent that from happening, but what matters is that the default usage doesn't match our current needs.

The issue came to the forefront when we added the `--all` option. 

What to do: replace the `--freeze` option with an `--update` option.

* not updating becomes the default
* adding new behaviors becomes much simpler

Make sure to clean up the `--all` logic to be sure it is still correct.

**Comment by Insti** [comment]
Thanks for the reminder stalebot
