### ISSUE TITLE
generator: refinements and lexical scope.

### ISSUE THREAD

**Issue by Insti** [exercism/ruby#645]
context: https://github.com/exercism/xruby/pull/583#pullrequestreview-37758023

Make the underscoring helper methods available to <problem>_cases without them having to remember to include 'using Generator::Underscore'

(This may involve not using refinements.)

**Comment by ajwann** [comment]
I attempted to force inheritance of the refinement with the ```inherited``` hook, with no luck. If we really want the methods declared on the String and Fixnum classes, we could do a regular monkey patch. Otherwise I think the best option is to just make them protected methods on the ```ExerciseCases``` class.

**Comment by Insti** [comment]
> make them protected methods on the `ExerciseCases` class

I think this is a good idea, do you want to take a shot at a PR for this?

**Comment by Insti** [comment]
Still relevant

**Comment by ajwann** [comment]
I can probably put up a PR this weekend, unless someone beats me too it.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by Insti** [comment]
Great :heart:
