### ISSUE TITLE
Discussion: Order exercises by complexity?

### ISSUE THREAD

**Issue by Insti** [exercism/ruby#663]
## Idea: 

Order the exercises by complexity with the simpler exercises first.

## Calculating complexity:

I've calculated the [Flog score](https://github.com/seattlerb/flog) (Other metrics are available.) for all the example solutions.

## Caveats:

The example solutions are of inconsistent quality.

## Questions:

How does the complexity ordering below compare to the current ordering?
Is this better/worse than the current ordering?
Should we analyse "typical" solutions rather than a specific solution?
Would this make getting started too boring?
Would this help avoid a 'hump' that causes people to get stuck and stop?

## Data:

```
1.0 hello-world
1.9 rna-transcription
2.5 flatten-array
3.1 gigasecond
4.0 pangram
4.3 accumulate
5.2 etl
6.7 isogram
7.5 robot-name
8.1 strain
8.4 allergies
10.1 point-mutations
10.2 prime-factors
11.1 grains
11.6 roman-numerals
11.7 word-count
12.1 acronym
12.1 hamming
12.4 sum-of-multiples
12.6 space-age
13.2 series
15.2 beer-song
15.3 grade-school
16.7 bracket-push
16.7 trinary
16.9 sieve
17.1 food-chain
17.3 octal
17.6 leap
18.0 phone-number
18.4 difference-of-squares
18.5 matrix
18.8 house
19.2 binary
19.6 nucleotide-count
20.2 scrabble-score
20.4 atbash-cipher
22.1 transpose
23.5 twelve-days
23.6 kindergarten-garden
23.6 nth-prime
25.1 hexadecimal
26.1 bob
26.1 secret-handshake
26.4 perfect-numbers
26.4 pig-latin
27.4 anagram
27.4 protein-translation
27.7 dominoes
27.9 run-length-encoding
28.4 luhn
28.6 proverb
29.9 clock
31.0 simple-linked-list
32.2 list-ops
32.9 linked-list
33.7 raindrops
33.9 binary-search-tree
34.0 all-your-base
34.1 crypto-square
35.5 circular-buffer
36.6 saddle-points
38.4 pascals-triangle
40.3 triangle
42.9 scale-generator
43.0 palindrome-products
43.9 binary-search
45.8 diamond
49.2 meetup
52.9 largest-series-product
53.6 robot-simulator
56.7 ocr-numbers
56.7 simple-cipher
58.3 wordy
60.4 pythagorean-triplet
68.5 queen-attack
68.7 rail-fence-cipher
71.7 tournament
86.2 two-bucket
91.7 custom-set
114.5 say
117.7 minesweeper
119.9 connect
126.0 bowling
128.8 alphametics
138.4 poker
```

**Comment by kotp** [comment]
The flog value may not accurately reflect the ease in which an exercise is solved.  What other metrics could be considered?

It very well be the best we have to start with though.

**Comment by Insti** [comment]
I'll close this and open it again if it becomes relevant again once we know what is happening with the new 'path' based exercise ordering. It may be a way to order exercises in branches.
