### ISSUE TITLE
leap: Tests should not monkeypatch Date.

### ISSUE THREAD

**Issue by Insti** [exercism/ruby#666]
https://github.com/exercism/xruby/blob/master/exercises/leap/leap_test.rb#L6
```
class Date
  def leap?
    raise RuntimeError, "Implement this yourself instead of using Ruby's implementation."
  end

  alias gregorian_leap? leap?
  alias julian_leap? leap?
end
```

Using Ruby's built-in leap year method should be a valid solution to this problem.

Note: This test is generated, so the `test_template.erb` will be the file to modify. Deleting the custom template completely might be a good solution.

https://github.com/exercism/xruby/blob/master/exercises/leap/.meta/generator/test_template.erb

**Comment by kotp** [comment]
See history from #14

The reason it is there is to help inform:
> If your language provides a method in the standard library that does
this look-up, pretend it doesn't exist and implement it yourself

Personally, once the goal is reached, I have no qualms in having the tests modified to allow the trivial solution.
