### ISSUE TITLE
Gigasecond: Test should require 'time' rather than the solution

### ISSUE THREAD

**Issue by kotp** [exercism/ruby#676]
I had been very careful about leaving the requirements of Time in the test file for Gigasecond, and then in PR #457 I let it slip.

Requiring time in the test file, rather than the solution lets the solution be written as a more flexible thing.

It allows for a little more exploration.

There are reasons to not change this, as it provides some fodder for discussing this.  It let's the talk about being able to modify tests and submitting them for exploration happen.

**Comment by Insti** [comment]
https://github.com/exercism/xruby/blob/master/exercises/gigasecond/gigasecond_test.rb

If `Time` is referenced in the test file the `require` should be in the test file.

I argue that having `Time` in the test file is the problem that should be solved.

**Comment by Insti** [comment]
http://exercism.io/exercises/ruby/gigasecond/readme

The Readme is not particularly helpful concerning inputs/outputs.

The [canonical-data](https://github.com/exercism/x-common/blob/master/exercises/gigasecond/canonical-data.json) seems to suggest that some kind of time object should be returned.

**Comment by kotp** [comment]
Yes, the canonical drives the tests... the intent may be a little harder to discern.  However, as is in my feedback for Gigasecond exercises commonly, the name of the object itself suggests that the units are "seconds", as a commonality.  So providing a number of seconds, perhaps even `12` or `12.75` and adding a gigasecond to it should reasonably result in `1_000_000_012.75` for the latter.

And I fully agree that the require 'time' should be in the test file, it is used as a convenience to the test.

Perhaps to help bring this out (at the expense of losing the person-to-person discussion about it), we could add a test that does exactly as described in the example above, in this message.

**Comment by kotp** [comment]
Turns out that time is required in the cases file... but not written to the test file.

**Comment by kotp** [comment]
Not a large enough concern.
