### ISSUE TITLE
Rename references to `exercism/xruby` to `exercism/ruby`.

### ISSUE THREAD

**Issue by kotp** [exercism/ruby#680]
We should change references to the URL from `exercism/xruby` to `exercism/ruby`.  No rush, as it will redirect, but for clarity.

Regarding references as pertains to the generator suite, from Katrina in #679:
> The test generators have some references to the xruby directory, but I don't have enough familiarity with this to start fiddling with it, so I left it alone.

**Comment by Insti** [comment]
There's a link to the gitter room in the README that can be updated.

**Comment by Insti** [comment]
`XRUBY_LIB` will need to become `EXERCISM_RUBY_LIB` or something `RUBY_LIB` seems like it would be too easily confused with an official RUBY constant.

**Comment by kotp** [comment]
The README links are fixed.

The `XRUBY_LIB` is internal to our code, and so no rush on this, if needed at all.  I agree about `RUBY_LIB` being the wrong name.

**Comment by rberecka** [comment]
Hi! I'm at the Write Speak Code Conference today, and it's Code day! I was wondering if this is still up for grabs?

**Comment by kotp** [comment]
Being attended to at least in part for PR #706

**Comment by Insti** [comment]
I think this is done now.

**Comment by Insti** [comment]
Just checked: there are still a few more references to xruby
```
./exercises/hello-world/.meta/generator/test_template.erb:  puts 'Minitest 5.0 gem must be installed for the xRuby track.'
./exercises/hello-world/hello_world_test.rb:  puts 'Minitest 5.0 gem must be installed for the xRuby track.'
./bash_completion:# Bash completion for the xruby test generate script
./test/generator/command_line_test.rb:      track: 'test/fixtures/xruby'
./test/generator/command_line/generator_optparser_test.rb:      track: 'test/fixtures/xruby'
./test/generator/files/metadata_files_test.rb:        track: 'test/fixtures/xruby'
```

**Comment by kotp** [comment]
Thank you @NeimadTL  and @Insti
