### ISSUE TITLE
hello_world: GETTING_STARTED.md references tests that aren't there.

### ISSUE THREAD

**Issue by chrisman** [exercism/ruby#681]
There is one test in hello_world_test.rb. GETTING_STARTED.md makes repeated references to three tests, two of which are skipped.

## Expected Behavior

Expected behavior is that the tests in hello_world_test.rb support the steps listed in GETTING_STARTED.md

## Current Behavior

Currently, GETTING_STARTED.md references code that is not there, and steps that are not possible to complete.

## Possible Solution

__Option 1__
Add two tests to hello_world_test.rb if you want to demonstrate how to un-skip tests, and run multiple tests.

This is probably the best option given the number of references to three tests in GETTING_STARTED.md, and the fact that the learner will be expected to know how to do this in future exercise.

__Option 2__
Change GETTING_STARTED.md so all references to three tests are removed, or rewritten to reference 1 test:

+ line 52 currently reads `3 runs, 0 assertions, 0 failures, 1 errors, 2 skips`. It could be changed to `1 runs, 0 assertions, 0 failures, 1 errors, 0 skips`

+ remove lines 77 - 84

+ remove lines 132 - 144

and then add instructions for how to un-skip a test in the next exercise?

**Comment by Insti** [comment]
Thanks @chrisman 

The `hello-world` exercise has evolved to be just a test that one can submit something,
So the best option is probably Option 2, moving the instructions about tests into the second exercise.

Is this something you would be able to help us with?

**Comment by chrisman** [comment]
Sure.

I'll edit GETTING_STARTED.md in the first exercise to remove references to multiple tests, and then add a GETTING_STARTED.md or a RUNNING_TESTS.md  to _hamming_, the second exercise.
