### ISSUE TITLE
Binary search tree exercise checks for version on Bst class instead of Bookkeeping module

### ISSUE THREAD

**Issue by Ryan1729** [exercism/ruby#696]
The [binary search tree exercise test](https://github.com/exercism/ruby/blob/5fc6cd30eabc9d90a8cef98fa95c29ba43b0b1dc/exercises/binary-search-tree/binary_search_tree_test.rb#L112) checks for `Bst::VERSION` instead of `BookKeeping::VERSION ` like the other exercises.

Not the biggest deal, but it's probably worth fixing if/when #513 is addressed.

**Comment by kotp** [comment]
If you would like, you can do the pull request regardless of the status of #513

**Comment by Ryan1729** [comment]
Ah, I wasn't sure if the exercise was generated or not, but given the absence of a `canonical-data.json` file in the [problem-specifications repo](https://github.com/exercism/problem-specifications/tree/1f8daa28fb98de2d8c85bf69f98f250eddd08c97/exercises/binary-search-tree) I suppose it isn't.
