### ISSUE TITLE
Strain tests should catch solutions relying on Array#-

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/ruby#726]
[This solution](http://exercism.io/submissions/f86397a7fdf242e09b3d87e42e413485) should not pass the tests.

## Expected Behavior
Some kind of tests should be introduced in which the block depends upon state outside just the argument passed into it to catch such solutions.

## Current Behavior
Tests pass.

## Possible Solution
Use global variable as a tracker of external state.

## Steps to Reproduce (for bugs)

```ruby
$i = 0 # => 0
[1,2,3,1,1,1,1,1].keep do |e| 
  keep = $i == 0
  $i += 1
  keep
end # => [1]
```

This works as expected, but now try a similar approach with `discard`.

```ruby
$i = 0 # => 0
[1,2,3,1,1,1,1,1].discard do |e| 
  discard = $i == 0
  $i += 1
  discard
end # => [2, 3]
```

It deletes all `1`s, not only the one at index 0.

**Comment by Insti** [comment]
See also: https://github.com/exercism/ruby/issues/406

**Comment by Insti** [comment]
Still relevant.

**Comment by Insti** [comment]
Thanks for the bump stalebot
