### ISSUE TITLE
queen-attack: fix test generator 

### ISSUE THREAD

**Issue by Insti** [exercism/ruby#741]
The queen-attack test generator is broken.

This is probably due to an update in the structure of the canonical-data.json file from the problem-specifications repository.

The file that needs to change is probably: https://github.com/exercism/ruby/blob/master/exercises/queen-attack/.meta/generator/queen_attack_case.rb

To reproduce:

Make sure you have the latest problem-specifications repository checked out.
run: `bin/generate queen-attack`

**Comment by cored** [comment]
@Insti I would like to work on this one.

**Comment by Insti** [comment]
Great. let me know if you need any help.
Either here or in the gitter chat room: https://gitter.im/exercism/ruby
