### ISSUE TITLE
two-bucket: update example solution.

### ISSUE THREAD

**Issue by Insti** [exercism/ruby#749]
The common test data for two-bucket problem has been updated.

This pull request updates the Ruby track tests to match: https://github.com/exercism/ruby/pull/746

But the example solution no longer passes the tests.

**Task:**

Update (or replace) the [example solution](https://github.com/exercism/ruby/blob/master/exercises/two-bucket/.meta/solutions/two_bucket.rb) so that it passes the new tests.

This will probably require checking out and making a Pull Request against my fork/branch: https://github.com/Insti/exercism-ruby/tree/Two-bucket-regenerate_tests which contains the updated tests. (This will still count toward Hacktoberfest)

**Comment by kvsm** [comment]
🌮

**Comment by Insti** [comment]
Thanks @kvsm :heart:
