### ISSUE TITLE
pig-latin: update example solution

### ISSUE THREAD

**Issue by Insti** [exercism/ruby#750]
The common test data for the pig-latin problem has been updated.

This pull request updates the Ruby track tests to match: https://github.com/exercism/ruby/pull/745

But the example solution no longer passes the tests.

**Task:**

Update (or replace) the [example solution](https://github.com/exercism/ruby/blob/master/exercises/pig-latin/.meta/solutions/pig_latin.rb) so that it passes the new tests.

This will probably require checking out and making a Pull Request against my fork/branch: https://github.com/Insti/exercism-ruby/tree/Pig-latin-regenerate_tests which contains the updated tests. (This will still count toward Hacktoberfest)

**Comment by kvsm** [comment]
I'll take this on. :)

**Comment by Insti** [comment]
Thanks @kvsm :heart:
