### ISSUE TITLE
accumulate: test case for when there is no block given

### ISSUE THREAD

**Issue by kiriakosv** [exercism/ruby#766]
I want to add a test case in the accumulate problem. Specifically, this test case would ensure that the method returns the initial array if no block is given. Should I proceed?

**Comment by kiriakosv** [comment]
An alternative would be to test that the method returns an Enumerator.

**Comment by Insti** [comment]
Have you read through this discussion: https://github.com/exercism/ruby/pull/395

**Comment by Insti** [comment]
@kiriakosv I recommend reading through that thread, and if you still think adding the test is a good idea you can make a PR and we can discuss it further. I assume you've already written the the test as part of your own solution.
