### ISSUE TITLE
minesweeper: tests should expect ArgumentError

### ISSUE THREAD

**Issue by abeger** [exercism/ruby#778]
## Expected Behavior

The Minesweeper tests should expect `Board.transform` to raise `ArgumentError` when the method is passed invalid data.

## Current Behavior

The tests expect `Board.transform` to raise `ValueError`, which is different from all other Ruby exercises.

## Possible Solution

Replace `ValueError` with `ArgumentError`.

**Comment by Insti** [comment]
Sounds reasonable 👍 

Do you want to make a pull request for this?

The file to change would be: https://github.com/exercism/ruby/blob/master/exercises/minesweeper/minesweeper_test.rb

**Comment by abeger** [comment]
I've got the change in the hopper. I'll try to get to a PR today.

**Comment by abeger** [comment]
Submitted!

**Comment by Insti** [comment]
Resolved by #779
