### ISSUE TITLE
Travis CI build is failing with Disk Quota Exceeded error.

### ISSUE THREAD

**Issue by kotp** [exercism/ruby#788]
The travis-ci job for PR# 787 is failing, while the full message can be seen [here](https://travis-ci.org/exercism/ruby/jobs/323747212), the short version is:

> oci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"

**Comment by kotp** [comment]
It looks like Travis is having some issues, they are looking into it.

**Comment by Insti** [comment]
This seems to have resolved itself.
