### ISSUE TITLE
Accumulate: Partial test case for no block given

### ISSUE THREAD

**Issue by matthew-campbell** [exercism/ruby#795]
The test case for when no block is provided allows invalid implementations to work. The test passes when a user writes `return to_enum unless block_given?` because the default parameter for `to_enum` --`:each`-- is silently passed along.

Adding a test case (to the readme) to ensure the enumerator is not just an enumerator, but the correct enumerator would resolve this issue.

For example:

```ruby
def test_accumulate_squares_when_no_block_is_passed
  enum = [1, 2, 3].accumulate
  result = enum.each { |number| number * number }
  assert_equal [1, 4, 9], result
end
```

See related: 
- #395
- https://github.com/exercism/ruby/blob/master/exercises/accumulate/README.md

**Comment by kotp** [comment]
It would be "Adding a test case (to the readme)" you mean adding a test case to the test file?

@matthew-campbell Can you make that change in the appropriate place as a pull request?

**Comment by Insti** [comment]
The Readme is the correct place to add this particular test.
I would suggest editing the existing Readme based test.

**Comment by kotp** [comment]
I mistook it for the more general readme.  Thanks @Insti
