### ISSUE TITLE
connect: README incorrectly describes test data

### ISSUE THREAD

**Issue by abeger** [exercism/ruby#810]
From the README of the "connect" exercise (emphasis mine):

> The boards look like this (with spaces added for readability, **which won't be in
> the representation passed to your code**):
> 
> ```text
> . O . X .
>  . X X O .
>   O O O X .
>    . X O X O
>     X O O O X
> ```

But if you look at the representation passed to your code:

```ruby
    board = [
      'X O . .',
      ' O X X X',
      '  O X O .',
      '   . O X .',
      '    X X O O'
    ]
```

**Comment by Insti** [comment]
Hmm you are correct.
I think the space based representation is fine in the test file, but it probably needs 
Something like: `.map{ |string| string.sub(/^ */,'') }` added to the declaration of `board` to strip out the whitespace before the board is passed to game.

**Comment by Insti** [comment]
https://github.com/exercism/ruby/blob/master/exercises/connect/.meta/generator/connect_case.rb is probably the place to do this.

**Comment by Kacppian** [comment]
Can I work on this?

**Comment by Insti** [comment]
@Kacppian sure! :+1:
