### ISSUE TITLE
Getting the Ruby track in better shape for the new site

### ISSUE THREAD

**Issue by iHiD** [exercism/ruby#815]
The new site has now launched and despite Ruby being one of the most popular Tracks, it's lagging behind in terms of being correctly configured on the new experience. 

Specifically we're missing:
- Topics
- Difficulties
- An unlocking path

All of these things are defined in the [config.json](https://github.com/exercism/ruby/blob/master/config.json).

We should have 4 or 5 exercises that are `"core": false, "unlocked_by": nil`. These are bonus exercises that will be available as soon as you join the track, along with the first core exercise.

Then, each core exercise should have a handful of exercises that will be unlocked when you complete it. So if `hamming` is a core exercise, then you might have 6 or 7 exercises that are `core: false, "unlocked_by": "hamming"`.

We have a tool, [Configlet](https://github.com/exercism/configlet/releases/latest), that you can download to help structure the unlocking. Run the `tree` command with the path to the root of a track repository (or `.` from within the root of the repo). This will show you which exercises depend on which core exercises.

```
$ configlet tree .
```

It would be incredibly helpful if people could provide PRs with topics and difficulties. If anyone wants to take responsibility for structuring some or all of the unlocking behaviour that would be amazing too. 

The following Tracks are good examples: 

- [Go](https://github.com/exercism/go/blob/master/config.json)
- [C#](https://github.com/exercism/csharp/blob/master/config.json)
- [R](https://github.com/exercism/csharp/blob/master/config.json)

Thanks!

(cc @exercism/ruby)

**Comment by Insti** [comment]
It would be good if someone could copy the topics and unlock tree from the Go track so we have a better starting point.

Note that we can't just copy the `config.json` file directly since we need to keep our own UUIDs

**Comment by Insti** [comment]
Yes :+1:

**Comment by F3PiX** [comment]
O cool @koppen !  Are you also going to fill in the 'unlocked_by's' or shall I work on that after your PR is merged?

**Comment by koppen** [comment]
I have filled them in to the best of my knowledge based on the progression
in the Go track.

It could probably do with some more work but I wasn’t sure how to decide
what unlocks what.

Den 27. juli 2018 kl. 12.52.48, Maud de Vries (notifications@github.com)
skrev:

**Comment by Insti** [comment]
Working on the unlocks after we get #818 merged is probably best.

**Comment by minaslater** [comment]
It seems that #818 has already been merged. Has anyone begin work on the unlocks?

**Comment by F3PiX** [comment]
Yes, I am on it. Planning to do a PR this weekend, for the first few exercises.

**Comment by Insti** [comment]
I believe the majority of the work for this has been completed. 
The first draft unlocking tree has been set up and topics and difficulties are slowly being added as people come with suggestions.

@F3PiX is doing a great job of continuing on working out the right ordering of exercises. :heart:
