### ISSUE TITLE
All exercises unlocked, should they be?

### ISSUE THREAD

**Issue by mikewalker** [exercism/ruby#822]
I have completed a few exercises in Ruby and I used to have to complete an exercise in the progression before the next exercise was unlocked. Now every exercise is unlocked, both core and extra exercises. Was this change intentional?

**Comment by Insti** [comment]
No. I suspect something is wrong. Thanks for letting us know.

**Comment by Insti** [comment]
I've created an issue in the main exercism.io repository.

I assume your account also existed in Exercism V1

**Comment by mikewalker** [comment]
Yes my account also existed in v1,.

**Comment by mikewalker** [comment]
@Insti I think we can close this one now too.
