### ISSUE TITLE
Run minitest with benchmark

### ISSUE THREAD

**Issue by guygastineau** [exercism/ruby#833]
Does anyone know how I can do this while testing an exercise?

**Comment by Insti** [comment]
What are you trying to do?

There's this: https://chriskottom.com/blog/2015/04/minitest-benchmark-an-introduction/

**Comment by guygastineau** [comment]
Thanks for the link. I'm just trying to compare efficiency of two of my iterations with more info than just time. Like benchmem test or something.

**Comment by Insti** [comment]
For that I'd use the `Benchmark` library: https://ruby-doc.org/stdlib-2.5.0/libdoc/benchmark/rdoc/Benchmark.html

Or something like https://github.com/michaelherold/benchmark-memory if you care about memory.

Or just work things out logically by working out how many loops you're doing and/or how many things you are allocating.

Or ask for performance related comments from your mentor.

It all depends a lot on what you are trying to do / optimize for.

**Comment by guygastineau** [comment]
Thank you for the information.  Mostly I know from `working things out logically` that the solution is much more efficient than most approaches.  I wanted to see by how much, and include memory.
