### ISSUE TITLE
Extra newline characters causing formatting issues in readme files

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/ruby#835]
It seems that a number of the README files have unnecessary newline characters which are causing formatting issues when they are displayed on the website. For instance, I have marked several issues in the README for the Matrix exercise:

![readme](https://user-images.githubusercontent.com/1254212/44124124-9417f490-9ff9-11e8-906c-d549450f8ea2.png)

**Comment by PatrickMcSweeny** [comment]
I have a pull request pending in the website repo that would fix this issue without having to modify the readme files themselves.

**Comment by Insti** [comment]
For the curious: https://github.com/exercism/website/pull/342
