### ISSUE TITLE
Remove obsolete version tracking assertions in exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/ruby#836]
Some tracks have added assertions to the exercise test suites that ensure that the solution has a hard-coded version in it.
In the old version of the site, this was useful, as it let commenters see what version of the test suite the code had been written against, and they wouldn't accidentally tell people that their code was wrong, when really the world had just moved on since it was submitted.

If this track does not have any assertions that track versions in the exercise tests, please close this issue.

If this track _does_ have this bookkeeping code, then please remove it from all the exercises.

See https://github.com/exercism/exercism/issues/4266 for the full explanation of this change.

**Comment by kytrinyx** [comment]
Ruby has this. It's the `BookKeeping::VERSION`

**Comment by F3PiX** [comment]
- Wouldn't it be confusing when looking at the community solutions? We don't see the associated tests there, but in the solution we can see at least if it's written with a different version of the tests than our own version. That goes away now, right?
- Also, as a mentor, how will I be able to tell that my own solution (or my notes, or the mentor notes) is different from the version the student submitted? 
- Will the test tab show the _students_ version of the tests?

**Comment by kytrinyx** [comment]
> Wouldn't it be confusing when looking at the community solutions?

I'm totally fine with that.

> Also, as a mentor, how will I be able to tell that my own solution (or my notes, or the mentor notes) is different from the version the student submitted?

That's a good question. I think that as a mentor, if in doubt, we should download and run the tests.

> Will the test tab show the students version of the tests?

Yes! That was buggy, and has been fixed.

**Comment by F3PiX** [comment]
I weep a little... But as everyone else seems to hate them, I'll weep quietly ;-)

**Comment by kytrinyx** [comment]
❤️ What if the tests included a version number but we didn't include any assertions for them?

Also: potentially we could make it so you can ask to see the test suite on the community part of the site...?

**Comment by F3PiX** [comment]
> What if the tests included a version number but we didn't include any assertions for them?
❤️  That would help! Thanks for asking!  I appreciate that. But I still think that mentoring will be harder without the version readily available. Especially during the period that we have legacy solutions with potentially older versions, and the current versions, and maybe newer versions when we are working on restructuring the Ruby track.  

Same for the community part, It would help, but I don't see that it's a better user experience. Unless 💡  we only show the latest versions of the community solutions! 

And we also have the mentor notes to consider. It will be harder to communicate the differences in versions over there too. 

But yeah, being able to find the version _somewhere_ would definitively help.

**Comment by kytrinyx** [comment]
@F3PiX I think this is a valuable conversation--and one that we should have at the product-level rather than the track level.

Would you mind opening an issue in http://github.com/exercism/exercism/issues so that we can track it for when we have the bandwidth to dig in?
