### ISSUE TITLE
Remove references to BookKeeping from readme.

### ISSUE THREAD

**Issue by Insti** [exercism/ruby#838]
As of: https://github.com/exercism/ruby/issues/836 the `BookKeeping` section is no longer used in the exercise test cases.

The documentation in the readme can also be removed.

TODO: 

Remove the [BookKeeping::VERSION section](https://github.com/exercism/ruby#bookkeepingversion) from the ruby repository `Readme.md`: https://github.com/exercism/ruby/blob/master/README.md

**Comment by kevinsamoei** [comment]
@Insti In the `Readme.md` we also have a part in the `Regenerating a Test Suite` section that mentions updating `BookKeeping::VERSION number` when you run `generate`. Is this part as well being removed?

**Comment by Insti** [comment]
@kevinsamoei well spotted! :heart: 

Yes that should also be removed.

**Comment by kevinsamoei** [comment]
@Insti Awesome. Pull request coming up.
