### ISSUE TITLE
Remove "version" related code from test generator.

### ISSUE THREAD

**Issue by Insti** [exercism/ruby#840]
As of: https://github.com/exercism/ruby/issues/836 the `BookKeeping` section is no longer used in the exercise test cases.

The test generator contains code to update the BookKeeping version number in the test cases and example solutions. 

This code is no longer required and can be removed.

TODO: 

Remove version related things from the test case generator.
This includes:

* Command line option.
* Generator unit tests.
* Generator source code.
* All the `exercise/*/.meta/.version` files.
* (new!) Documentation in the README.md file 
* Anything else you can find that I've forgotten.

**Comment by jpotts244** [comment]
Hi @Insti 👋 , would love to help out with this one!

**Comment by Insti** [comment]
Super! Let me know if you have any questions.

**Comment by F3PiX** [comment]
@insti Can this be closed?

**Comment by Insti** [comment]
Yes.
