### ISSUE TITLE
protein-translation: Codon Protein Table is not rendered correctly on the HTML page

### ISSUE THREAD

**Issue by ehom** [exercism/ruby#857]
https://exercism.io/my/solutions/f55a4cdbc7d4451f85836299ffccd057

I see a markdown table embedded inside paragraph tags

<p>Codon                 | Protein
:---                  | :---
AUG                   | Methionine
UUU, UUC              | Phenylalanine
UUA, UUG              | Leucine
UCU, UCC, UCA, UCG    | Serine
UAU, UAC              | Tyrosine
UGU, UGC              | Cysteine
UGG                   | Tryptophan
UAA, UAG, UGA         | STOP</p>

---

Thank you for this great learning tool.

🐼

**Comment by Insti** [comment]
Thanks for reporting this @ehom.

This needs some more research to work out if it is a problem with the markdown in the readme or Exercism's markdown renderer, (or both).

Rendered version can be found here: https://exercism.io/tracks/ruby/exercises/protein-translation/solutions/b24e3d641e5e4b0095b65982f64ac1e8
(if you click on "instructions")

Readme source can be found here: https://github.com/exercism/ruby/blob/master/exercises/protein-translation/README.md
(Renders fine in github.)


If it's the renderer you will need to investigate the website code: https://github.com/exercism/website

Or raise an issue here: https://github.com/exercism/exercism/issues

**Comment by F3PiX** [comment]
Update. This is the current rendering on the Instructions page. Looks good to me. Can we close this?
![schermafbeelding 2018-12-15 om 12 09 42](https://user-images.githubusercontent.com/6314687/50042387-669ef800-0062-11e9-8b63-d3df64c1a4d1.png)

**Comment by Insti** [comment]
Looks fixed.
