### ISSUE TITLE
Twelve days out of sync with specification

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/ruby#858]
The problem specification for Twelve Days was changed to correct a punctuation issue.

https://github.com/exercism/problem-specifications/blob/84aa47979df7f526bdcb777cacc2c2cc9647dcaa/exercises/twelve-days/description.md

**Comment by Insti** [comment]
https://github.com/exercism/problem-specifications/issues/1328
https://github.com/exercism/problem-specifications/pull/1329
