### ISSUE TITLE
binary-search-tree: test_inserting_same may be inaccurate/confusing

### ISSUE THREAD

**Issue by BradleyJohnson** [exercism/ruby#861]
```ruby
  def test_inserting_same
    four = Bst.new 4
    four.insert 4
    assert_equal 4, four.data
    assert_equal 4, four.left.data
  end
```

As I understand it, this test asserts for the behavior of a binary tree rather than a binary search tree. Adding a duplicate value should probably throw an exception or simply drop the duplicate, right? Happy to open a PR for this if folks agrees.

**Comment by BradleyJohnson** [comment]
@Insti Canonical data agrees with the current implementation. I suppose the behavior of duplicate inserts is dependant on application rather than some strict interpretation of the data structure. I'll close this, sorry for the noise!

**Comment by Insti** [comment]
It is always possible that the canonical-data is incorrect.

Thanks for making an issue anyway :heart:
