### ISSUE TITLE
'High Scores' solution page is completely blank

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/ruby#898]
I had started working on the 'High Scores' exercise a while back but never finished. When I went to the solution page this morning all I see is this:

![screenshot from 2018-12-13 08-48-07](https://user-images.githubusercontent.com/1254212/49945385-c65a9f00-feba-11e8-85ea-13dbc97f7fb5.png)

**Comment by Insti** [comment]
It's probably worth posting this in the main exercism repository.

**Comment by F3PiX** [comment]
@PatrickMcSweeny Is this still a thing?

**Comment by PatrickMcSweeny** [comment]
@F3PiX  I just checked again and the problem persists.

**Comment by F3PiX** [comment]
@PatrickMcSweeny It sounds weird. However, as there's an issue now in the main repository, I'm closing this here. Please reopen if necessary!

**Comment by F3PiX** [comment]
We can reopen if it's not a main website code. That seems more probable than it being a Ruby Repo issue as far as I can see.
