### ISSUE TITLE
We need more exercises!

### ISSUE THREAD

**Issue by emcoding** [exercism/ruby#900]
This is a general overview of exercises to be added to the Ruby track. 
We'll discuss specifics in separate issues. 

1)  More easy exercises
- [ ] A simple hash exercise, that uses a hash as a lookup table without the need for advanced Enumerable methods -> in the making 
- [ ] A simple Datetime exercise: Gigasecond is a candidate. The Ruby track implementation is more barebone than the original https://github.com/exercism/problem-specifications/blob/master/exercises/gigasecond/canonical-data.json ; let's research if we can go with the original.  
- [ ] In PR : #893 Adding ArmstrongNumbers exercise  by @tuxified
- [ ] An easy 'frozen string literal' exercise ( thanks @kotp). This could be one of the exercises where we provide a `frozen_string.rb` file with the magic comment, in the download.  
- [ ] An easy Cº/Fº converter (introducing floats, maybe introducing `alias` `metric` for `to_celcius)

2) Some tracks have refactor exercises, and that looks like an interesting way to create more variation in the kind of exercises. It would be great to have one of this on different levels. 
- [ ] `Leap` looks like a candidate. We could provide a file with the `naive` implementation with `return false and true`'s that passes the tests. Then ask to refactor. 
- [ ] `Raindrops` is also a candidate. Provide a file with the naïve implementation and ask to refactor. 
- [ ] `Markdown` is [designed as a refactoring exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/markdown/description.md), but we don't have it in Ruby yet. 
Let's add it. 

3) Find more non-math exercises in the [Problem Specifications](https://github.com/exercism/problem-specifications)
Math-y exercises are well represented in the Ruby Track, and we could use some more non-math exercises as well. Especially on the easier levels. 
- [ ] Find interesting/fun, non-math exercises in the problem specifications, that can be added to the Ruby Track. Especially for people who know other tracks as well: maybe you know of exercises that were fun to do? Please leave a comment here with suggestions.

 
 If you're interested in working on any of these, please comment, so I can make a separate issue where we can discuss specifics. 🎉

**Comment by kytrinyx** [comment]
This issue is a few years old, and we've added a number of exercises in the interim.

While we always welcome more exercise ideas, I'm going to go ahead and close this, and if someone would like to work on a new exercise, they can open an issue to discuss the specifics.
