### ISSUE TITLE
Pythagorean Triplet: README and tests don't match

### ISSUE THREAD

**Issue by RiderSargent** [exercism/ruby#909]
The current `README` asks for the product of the factors for the triplet with a sum of 1000:
> There exists exactly one Pythagorean triplet for which a + b + c = 1000.
> Find the product a * b * c.

But the tests do not check for that, instead checking for a `where` method that receives a `max_factor` and optional `min_factor` and `sum` args.

I also noticed that the canonical [problem spec](https://github.com/exercism/problem-specifications/blob/master/exercises/pythagorean-triplet/description.md) was [recently updated](https://github.com/exercism/problem-specifications/commit/4599c2ecbd5ff03d098b4a6eaaea0ab7dbc518db#diff-9da7e22dbe347e9b76f623fc31b66a22).

I'm happy to submit a Pull Request for an added test for the "product when sum == 1000" case and/or an update to the `README`, but I'm not sure which direction the maintainers would like to go with that.

**Comment by Insti** [comment]
#910 is merged, so I think we can close this. Thanks @RiderSargent
