### ISSUE TITLE
Generate things

### ISSUE THREAD

**Issue by F3PiX** [exercism/ruby#913]
@pgaspar Thanks for helping 💙 

This things are ready to be generated:
- [x] Series Readme (to include the hints.md) but NOT the canonical data tests. #911 
- [x] OCR: Readme (to include the hints.md) #901
- [ ] ~High Scores adjustments?~

**Comment by pgaspar** [comment]
@F3PiX took me a bit to realize the hint files were on open PRs #912 and #901 😅 I'm not sure if I have write permissions for this repo yet, but that'd be useful to contribute to the PR branches directly. cc @Insti

**Comment by F3PiX** [comment]
Sorry for the cryptic description Pedro. I'll ping you when there's a bunch ready to go. And I added the PR's, good point, thanks.

**Comment by F3PiX** [comment]
@pgaspar Could you run the Readme's for Series and OCR please? The adjustments for High Scores will take a while.

**Comment by pgaspar** [comment]
@F3PiX I marked this issue as resolved by the PRs above, so this will be closed when they are merged. I think it's best to have smaller issues for each thing we need to generate instead of having a long running issue that may confuse new comers. Hope that's ok!

**Comment by F3PiX** [comment]
That's perfect. Thanks.
