### ISSUE TITLE
Word Count: minimal solution for approval

### ISSUE THREAD

**Issue by F3PiX** [exercism/ruby#915]
PR https://github.com/exercism/website-copy/pull/709  updates the Mentor Notes for Word Count's upcoming promotion to a core exercise. 
This is the Minimal Solution for Approval that is currently listed:

```ruby
class WordCount
  WORD_REGEX = /\b[\w']+\b/

  def initialize(phrase)
    @phrase = phrase
  end

  def word_count
    words.each_with_object(Hash.new(0)) do | word, count |
      count[word] += 1
    end
  end

  private

  def words
    @phrase.downcase.scan(WORD_REGEX)
  end
end
```

Your thoughts please! Both on the correctness of this solution and the 'minimalness'.
The [Notes PR](https://github.com/exercism/website-copy/pull/709) gives more background info.

**Comment by F3PiX** [comment]
@exercism/ruby ^

**Comment by kotp** [comment]
> The Notes PR gives more background info

Can you link that PR in the [description above](https://github.com/exercism/ruby/issues/915#issue-401006807)?

**Comment by SleeplessByte** [comment]
(exercism/website-copy#709 was merged -- I think this was great :))

**Comment by kotp** [comment]
This solution looks fine to me.  I would rename the constant, we don't say `WORDS_ARRAY = ['an', 'apple', 'a', 'day']` we know it is an array.  We should not use the `_REGEX` part of the name, we can see that it is a regular expression.  If we can't, in either case, we can inquire about the class of that object.

**Comment by F3PiX** [comment]
That's a good point. The PR with the notes is merged already, so this would require a new PR.

I'm closing this issue.
