### ISSUE TITLE
Test: Check if maintainers mentioning works

### ISSUE THREAD

**Issue by F3PiX** [exercism/ruby#920]
I'm trying to find out what this mention is doing, or that we'll need to create a maintainers team
@exercism/ruby 

Pedro, Victor, Geoff, are you getting a mention, different from the usual track watching mentions?

**Comment by kotp** [comment]
![notifications](https://user-images.githubusercontent.com/16747/51495911-fd5e8300-1d8b-11e9-96cb-e2f36b0dcd06.png)

I did get them in here (which is how I usually keep track of everything).

**Comment by F3PiX** [comment]
Cool!  @Insti Do you receive too?
