### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by emcoding** [exercism/ruby#925]
- [ ] "Don't use whitespaces in markdown to start on a new line; use double line breaks instead." https://github.com/exercism/ruby/pull/916#issuecomment-456246949  
- [ ] `@maintainers/ruby` in the template, to make sure maintainers get pinged.

**Comment by kytrinyx** [comment]
We are currently considering exercism-wide issue and PR templates, and I think that in the interim we can continue as we have been, with no PR template.

I would be in favor of closing this issue.
