### ISSUE TITLE
Temporarily not accepting changes to some exercises

### ISSUE THREAD

**Issue by emcoding** [exercism/ruby#935]
A massive overhaul of the Ruby track is currently underway.
One of the side effects is that changes to current exercises can have a huge impact on the new structure, unknown to the contributor.

Therefore, we don't accept changes, at least not without discussing them in an issue first, for the exercises listed below.
Other exercises, including adding new, have less impact to the Track Anatomy in general. (We still prefer an issue first, before a PR.)
In case your looking to contribute, check this issue: https://github.com/exercism/ruby/issues/900 for our wishlist. 

Thanks for your understanding! 

---

Hello World
Two Fer
Resistor Color Duo
Acronym
High Scores
Matrix
Series 
Word Count
Hamming
Raindrops
Isogram
Scrabble Score
Luhn 
Clock
Twelve Days
Tournament

ETL
Grep
Phone Number
Proverb
Resistor Color Trio

**Comment by kenliu** [comment]
any update on this?

**Comment by kotp** [comment]
Are we due a status update on this... @F3PiX

**Comment by F3PiX** [comment]
Yes, we are. 

My thinking is to add a list here of exercises we don't accept changes for, at least not without discussing it in an issue first. I'm thinking of the core exercises, and some exercises that are currently researched as core candidates. 

How does that sound?
@exercism/ruby

**Comment by F3PiX** [comment]
I updated the description with the list of exercises.

**Comment by kotp** [comment]
How about new exercises coming in...

**Comment by F3PiX** [comment]
I don't think everyone of those needs to be under Track Anatomy scrutiny. If needed, I'll explain. For new exercises it's mostly the start of the track that I'd worry about. In general, more exercises is more for us and for students to choose from :-)  

But! I'll add a link to exercises we _are_ looking for help for.

**Comment by kotp** [comment]
Well, 'reverse' is probably at the beginning... Can you give your thumbs up over there... it is the reason I realized we needed an update over here.
