### ISSUE TITLE
Exercises depend on regular expression too much

### ISSUE THREAD

**Issue by stt106** [exercism/ruby#937]
I think the exercises are putting a bit too much emphasis on regular expression. I would think the fundamental goal is to learn Ruby NOT regular expression. I don't have problems with regular expression itself but if I want to learn regular expression then exercism is probably not the best place compared to a dedicated site/book about regular expression.
I personally think the exercised should be designed to teach more about Ruby as a language. For instance, I can solve the `word count` exercise fairly quickly if the main aim is about counting the words using hash but instead it heavily relies on using regular expression to clean the words before counting it. This makes the whole exercise about regular expression rather than using hash, which I think is distracting for people who are trying to learn hash in Ruby.

**Comment by F3PiX** [comment]
Hi @sst106 Thanks so much for pointing this out. I totally agree with you that the goal is to get fluent in Ruby, and not per se in regular expressions. We're currently working on a project to restructure the track, meaning that we're looking both at all the exercises together, and at individual exercises. The role of regular expressions is absolutely a part of that, but to be honest: it's also not the highest priority at this moment. 
On the other hand: we're currently asking mentors to 'give away' the regular expressions, exactly for the reason you mention: that the goal is not to get fluent in regex.  That's one way to let regular expressions not get in the way of the exercise, and also take into account that they do play a part in Ruby methods. 
I will take your remarks on WordCount into account in the evaluation of the exercise. 
Thanks!

**Comment by F3PiX** [comment]
@stt106 #943 may interest you.

**Comment by kytrinyx** [comment]
Closing, as we're now quite happy with the focus of the practice exercises.
