### ISSUE TITLE
Pythagorean Triplet add restriction for execution time.

### ISSUE THREAD

**Issue by fanantoxa** [exercism/ruby#940]
Hi. I was working on [Pythagorean Triplet](https://github.com/exercism/ruby/tree/master/exercises/pythagorean-tripletl) and found it very interesting.
I've finished it with the combination and tried to check other solutions and found that in general everyone implement it also with full combinations.
This is very expansive way to generate Pythagorean Triplet.
Maybe we can add some time expectations for big calculations ?
I've found wiki article with different ways to calculate it: [Formulas for generating Pythagorean triples](https://en.wikipedia.org/wiki/Formulas_for_generating_Pythagorean_triples).
So we can add it to documentation so exercise will be more interesting that just getting all combinations ?

**Comment by kytrinyx** [comment]
I am sorry that you didn't get a response to this issue when you opened it (several years ago!).

I like that this exercise led you to explore—that's the ideal outcome of working on an exercise on Exercism, to my mind.

This doesn't really fit in the "instructions" part of the documentation, but would be perfect for the "approaches" part, which is unlocked after a student has solved the exercise and which they can use to dig deeper.

I know this is several years old, but if for some reason you find yourself with an itch to work on this, I would welcome a PR that adds an `.approaches` implementation for this exercise. You can see what would be included by looking at the PR for the `.approaches` for `two-fer` here: https://github.com/exercism/ruby/pull/1355/files
