### ISSUE TITLE
Matrix and saddle-points exercises overrides standard library class

### ISSUE THREAD

**Issue by fanantoxa** [exercism/ruby#941]
While I was completing exercises: [Matrix](https://github.com/exercism/ruby/tree/master/exercises/matrix) and [Saddle Points](https://github.com/exercism/ruby/tree/master/exercises/saddle-points). I've found that ruby already have a class in standard library that can hold and operate matrixes.
So as I see this exercise could be completed with some delegation or inheritance but we can't because test expect `Matrix` to be defined. 
Here is ruby reference: https://ruby-doc.org/stdlib-2.5.1/libdoc/matrix/rdoc/Matrix.html

**Comment by F3PiX** [comment]
Hi @fanantoxa. I moved this into an issue that addresses more issues about the Matrix exercise. So, I'm closing this one. Thanks!
