### ISSUE TITLE
refute Tests doesn't correspond to description

### ISSUE THREAD

**Issue by fanantoxa** [exercism/ruby#942]
Next test use `refute` to check if value if `false` and message say `false` but actually it checking for `falsey` which doesn't fail on `nil` and other `falsey` values.
Example:
https://github.com/exercism/ruby/blob/master/exercises/leap/leap_test.rb
```
....
refute Year.leap?(2015), "Expected 'false', 2015 is not a leap year."
....
refute Year.leap?(2100), "Expected 'false', 2100 is not a leap year."
....
````
https://github.com/exercism/ruby/blob/469e3751e37f7a9305903742470d323633e76ea1/exercises/isogram/isogram_test.rb
```
...
refute Isogram.isogram?(input), "Expected false, '#{input}' is not an isogram"
....
```

I'm sure it's more pleases where `refute` say that it have to be `false` but don't really check that it actually `false.

**Comment by Insti** [comment]
I don't think this is a problem, as long as the code being tested is returning a "truthy" value in true cases and a "falsey" value in false cases that should be good enough.

Especially since you really have to go out of your way to do the "wrong" thing in these exercises.

**Comment by fanantoxa** [comment]
@Insti Sorry, but I can't agree with that. That was thousands of issues and so many talks about `nil` that make bugs.
Also `<method_name>?` agreement tell that returning value should be `true|false` and nothing else.
And test say the same `Expected 'false'...`.
In practice you can go with TDD way (Like Sandi Metz propose) you fix your test one by one.
So for passing test `refute Year.leap?(2015), "Expected 'false', 2015 is not a leap year."`
you can descripe just 
```
def leap(yeap)
end
```
And it'll pass. But test say that it should be `false` not `nil`
So it expect
```
def leap(yeap)
  false
end
```
And this will be right one .

I assume that this exercises created for learning how to do things in right way. So why we can't make test to be fair too ?

**Comment by Insti** [comment]
Thanks, I agree with your arguments. 

Feel free to submit a PR that fixes the tests (and/or generators) to explicitly check for a boolean value.

**Comment by fanantoxa** [comment]
Working on PR

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this issue, as it's been a while since there was any movement on this discussion.
