### ISSUE TITLE
palindome-products: confusing test assertion

### ISSUE THREAD

**Issue by jdsutherland** [exercism/ruby#945]
I started working on this exercise and noticed something fishy about the first test case: https://github.com/exercism/ruby/blob/66c5ebe6e30e740785de75fc5440588803a62a19/exercises/palindrome-products/palindrome_products_test.rb#L10

I haven't completed the exercise yet (so I don't have a worked out understanding of why this might have been done) but it seems odd that the products are repeated and this seems to differ from other tracks:
[javascript](https://github.com/exercism/javascript/blob/065a4b287580978e2cbca6fd0db5df50e9898905/exercises/palindrome-products/palindrome-products.spec.js#L16)

[python](https://github.com/exercism/python/blob/1ea5ef9b5db26e4a2e4f0dc666d26455ec4b40e6/exercises/palindrome-products/palindrome_products_test.py#L30)

[go](https://github.com/exercism/go/blob/5446524b6b09c426dc743d078b5afc45eb9c135e/exercises/palindrome-products/palindrome_products_test.go#L29)

**Comment by jdsutherland** [comment]
I originally overlooked that this is using an `assert_includes` (rather than equals). I'm guessing that this is avoid failures due to array ordering. I'm not used to using minitest so maybe this is standard looking stuff.

Unless this seems worth taking action on, this can probably be closed.

**Comment by kotp** [comment]
See #305 for some backstory.

**Comment by kytrinyx** [comment]
Palindrome Products is now a part of the problem-specifications (language-agnostic test instructions and test cases), here:
https://github.com/exercism/problem-specifications/tree/main/exercises/palindrome-products

The exercise has undergone significant improvements in the past few years and this repository is up-to-date with the current changes as of this date.

I am going to go ahead and close this issue.
