### ISSUE TITLE
Clarify twelve days exercise instructions

### ISSUE THREAD

**Issue by kenliu** [exercism/ruby#956]
There was some [discussion in Slack](https://exercism-team.slack.com/archives/CARVB5V0R/p1554774426033900) about making the instructions more explicit so students build up the solution programatically and do not use the `test.txt` file as part of the solution.

Update the README to provide clearer instructions on this.

**Comment by kenliu** [comment]
see PR https://github.com/exercism/ruby/pull/957

**Comment by kotp** [comment]
Should be closed via #957
