### ISSUE TITLE
triangle: tests for the dig deeper section

### ISSUE THREAD

**Issue by gris** [exercism/ruby#963]
Hey, while I was doing the Triangle exercise, I did a few tests for the dig deeper section that checks for degenerate triangles. Do you think it is worth adding some tests for this functionality?

**Comment by kytrinyx** [comment]
Hello @gris, I'm so sorry that nobody responded to your suggestion five years ago.

If you do want to propose some extra tests I would recommend that you open an issue in the https://github.com/exercism/problem-specifications repository describing the test cases that you added, and discuss this with maintainers who manage the shared repository of test cases.

You can see the current list of test cases here: https://github.com/exercism/problem-specifications/blob/main/exercises/triangle/canonical-data.json
