### ISSUE TITLE
Reword sentence in Matrix Mentor Notes: help wanted

### ISSUE THREAD

**Issue by F3PiX** [exercism/ruby#976]
There's this sentence in the Matrix mentor notes:

```
For students who wrote code that interleaves string manipulation with data persistence, encourage them to do those steps sequentially.
```

I don't know if my English is lacking here, but I'd like to make this sentence easier to understand at first glance. Can someone please do a suggestion for a rewording?

Either here, or with a PR in the Website Copy repo. https://github.com/exercism/website-copy/tree/master/tracks/ruby/exercises/matrix

**Comment by briankung** [comment]
Maybe:

- > If students interleave string manipulation and data persistence, encourage them to perform the two as separate, sequential steps.

Or:

- > Encourage students to perform string manipulation and data persistence as separate, sequential steps (if they have not already done so).

Text in parentheses optional.

**Comment by kotp** [comment]
I think I like the second better.

**Comment by F3PiX** [comment]
Me too. 

I still have troubles understanding why it's in the notes. If it's a general advise on separation of concerns/single responsibility, then we usually don't add it to the notes. 
Or am I missing why this is specific to this exercise?

How about we just remove it. 

(@kotp)

**Comment by kotp** [comment]
I think that is the right thing to do... remove it.  If it is a problem we aren't seeing, it will come back... such is the nature of these things.

**Comment by F3PiX** [comment]
Removed :tada:
