### ISSUE TITLE
Proposal to un-core Matrix, find replacement

### ISSUE THREAD

**Issue by emcoding** [exercism/ruby#977]
This issue is extracted from #962.

Recap:
The Matrix exercise is partially problematic, or at least at its current position in the track. 
Problems are related to what should and shouldn't be done in an initializer, using a fabricator or not. Also, Ruby has its own Matrix class, and we don't want to ask students to reimplement existing features (at least not i core exercises).
There is, however, an interesting opportunity to discuss things with regard to computing the rows and the columns in the initializer. However, it is not appropriate for this level, and we found that it's harder to make a decision because there's no indication of what we need the rows and columns for.  

I quote (myself): 
> **All of the above leads to the conclusion that Matrix should be removed from the core progression.** On the other hand, it offers some features that we badly need on Level 2:
> 
> * a simple multiline string (or at least something else than a single line string)
> * private vs public
> * `map` with Symbol#to_proc
> * `attr_reader`
> * `memoization`
> 
> At the moment, there are no other exercises (that I know of) that can fill the gap if we remove Matrix from the core. Also, Matrix is one of only 2 exercises on Level 2 (Series being the other one, following Matrix).
> ...
> [let's] try to find (or create) one or more other exercises that can fill the gap that is currently filled by Matrix. 

1) Re: Replacement exercise: the upcoming exercise Resistor Color Trio will take care of: `private/public`, `attr_reader` and maybe `memoization`. 
2) The Transpose exercise, that is related to Matrix, does require to do further work with the rows and columns, so maybe that's an interesting replacement to work with matrices, but at a higher level -> let's investigate. It may be a Level 3 or 4 candidate.
3) Let's move Matrix to a side-exercise, as soon as Resistor Color III is ready to become core.
4) Let's investigate if the controversion in Matrix can be solved by re-thinking the tests. Maybe we can use multi-dimensional arrays as inputs, instead of strings? And use Ruby's Matrix library. (Just thinking out loud here, I didn't really look into this. See also https://github.com/exercism/ruby/issues/941)

**Comment by kytrinyx** [comment]
Since moving to v3 none of the practice exercises are part of a core curriculum. I'm going to go ahead and close this issue.
