### ISSUE TITLE
Things to be taken into account for the stub files

### ISSUE THREAD

**Issue by emcoding** [exercism/ruby#987]
Prep for #541 
Collection of things to take into considerations. Discussions welcome and preferably on Slack / track-ruby

- [ ] Implementation
- [ ] Comments in stub file: 
   - not alienating for experienced devs,
   - avoid the term 'stub file'
- [ ] Should the TDD instructions move to... somewhere? Or can they stay in the Readme? 
- [ ] This is an opportunity to add some scaffolding for writing instance methods instead of the current class methods, while the students still need to write one method only (because from a track anatomy point of view, we want to keep it to one line methods first).

**Comment by F3PiX** [comment]
Inspired by JS:
// Write your code for the 'Hello World' exercise in this file. 
// Make sure to look at hello_world_test.rb --that should give you some hints about what is
// expected here.

**Comment by kotp** [comment]
I believe the comment style of `//` is not valid for Ruby.  We can use mult-line comments there, if that is preferable.  But the file should be strictly valid Ruby.

**Comment by kotp** [comment]
```ruby
=begin
Write your code for the 'Hello World' exercise in this file. Make the tests in
hello_world_test.rb pass.

To get started with TDD, see the readme file in your
Hello World directory.
=end

class HelloWorld
  # your code here
end
```

**Comment by kytrinyx** [comment]
I'm closing this, as all exercises now have a stub file.
