### ISSUE TITLE
The Ruby track Exercises Tree

### ISSUE THREAD

**Issue by kotp** [exercism/ruby#989]
As of Thu Aug  8 17:00:24 UTC 2019

<details><summary>Ruby</summary>
====

core
----
├─ hello-world
│  ├─ gigasecond
│  └─ resistor-color
│
├─ two-fer
│  └─ rna-transcription
│
├─ resistor-color-duo
│  └─ leap
│
├─ acronym
│  ├─ pangram
│  └─ space-age
│
├─ high-scores
│  └─ triangle
│
├─ matrix
│  ├─ difference-of-squares
│  ├─ sum-of-multiples
│  ├─ anagram
│  └─ transpose
│
├─ series
│  ├─ grains
│  ├─ phone-number
│  ├─ flatten-array
│  └─ saddle-points
│
├─ word-count
│  ├─ etl
│  ├─ nucleotide-count
│  └─ pythagorean-triplet
│
├─ hamming
│  ├─ sieve
│  ├─ palindrome-products
│  ├─ proverb
│  └─ collatz-conjecture
│
├─ raindrops
│  ├─ nth-prime
│  ├─ bob
│  ├─ accumulate
│  ├─ strain
│  ├─ alphametics
│  ├─ matching-brackets
│  ├─ perfect-numbers
│  ├─ binary-search
│  └─ two-bucket
│
├─ isogram
│  ├─ run-length-encoding
│  ├─ rail-fence-cipher
│  ├─ allergies
│  ├─ scale-generator
│  ├─ minesweeper
│  ├─ robot-simulator
│  └─ all-your-base
│
├─ scrabble-score
│  ├─ beer-song
│  ├─ secret-handshake
│  ├─ wordy
│  └─ protein-translation
│
├─ luhn
│  ├─ robot-name
│  ├─ grade-school
│  ├─ binary-search-tree
│  ├─ crypto-square
│  ├─ atbash-cipher
│  ├─ pig-latin
│  ├─ simple-linked-list
│  ├─ simple-cipher
│  ├─ circular-buffer
│  ├─ change
│  ├─ dominoes
│  └─ list-ops
│
├─ clock
│  ├─ roman-numerals
│  ├─ prime-factors
│  ├─ house
│  ├─ poker
│  ├─ kindergarten-garden
│  ├─ largest-series-product
│  ├─ custom-set
│  ├─ linked-list
│  ├─ rotational-cipher
│  └─ affine-cipher
│
├─ twelve-days
│  ├─ bowling
│  ├─ say
│  ├─ meetup
│  ├─ ocr-numbers
│  ├─ diamond
│  ├─ isbn-verifier
│  ├─ complex-numbers
│  ├─ zipper
│  └─ grep
│
├─ tournament
│  ├─ queen-attack
│  ├─ food-chain
│  ├─ pascals-triangle
│  ├─ connect
│  └─ book-store
</details>

**Comment by kytrinyx** [comment]
I believe that this issue can be closed. If I am wrong about this, please reopen it with a comment about what needs to be done.
