### ISSUE TITLE
Resistor Duo is two times in the Ruby track 

### ISSUE THREAD

**Issue by rwobben** [exercism/ruby#996]
Hello, 

I think there is a exercise two times in the track with 2 different names. 
Im talking about : 

https://exercism.io/my/solutions/b8d06bf8cfb84674b3bd540870468d21 with the name Resistor Color Duo 

and : https://exercism.io/my/solutions/2380d05a1af441bf872e08006eab3c5a

under de name Resistor Color. 

Can one of the maintainerrs look at it. 

Roelof

**Comment by F3PiX** [comment]
@rwobben Hi Roelof, those are two different exercises: the first is about reading one color band's value, the second about reading two color bands and combining them. It's a series of exercises. Resistor Color Trio is coming soon :-)

**Comment by rwobben** [comment]
oke, then im sorry for the noise and willl close it
